package server

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	"github.com/rmmh/rose/meta"
	"github.com/rmmh/rose/storage"
)

// RebalancePolicy bounds how aggressively rebalance evens shard counts across
// active disks. The point is deliberately not to reach perfect balance: shards
// are expensive to move, so a little skew is tolerated and passes are rate
// limited.
type RebalancePolicy struct {
	// MinSkew is the hysteresis band. A pass is a no-op unless the busiest active
	// disk holds at least MinSkew more shards than the idlest, and it stops moving
	// once the spread falls back within the band. This is what keeps the system
	// from thrashing shards to flatten a one- or two-shard difference.
	MinSkew int
	// MaxMovesPerPass caps how many shards a single pass relocates, bounding the
	// IO one rebalance triggers. Zero means unbounded within a pass.
	MaxMovesPerPass int
	// Cooldown is the minimum wall-clock time between passes that actually moved
	// something; a pass started inside the window is skipped. This is the backoff
	// that stops a balanced-enough cluster from rebalancing on every tick.
	Cooldown time.Duration
}

// DefaultRebalancePolicy tolerates a two-shard spread, moves at most eight shards
// per pass, and waits five minutes between passes.
func DefaultRebalancePolicy() RebalancePolicy {
	return RebalancePolicy{MinSkew: 2, MaxMovesPerPass: 8, Cooldown: 5 * time.Minute}
}

// SetRebalancePolicy replaces the rebalance tuning. It is the operator knob for
// the hysteresis band, per-pass move cap, and backoff window.
func (s *Server) SetRebalancePolicy(p RebalancePolicy) {
	s.vlogMu.Lock()
	defer s.vlogMu.Unlock()
	s.rebalance = p
}

// DrainDisk evacuates every shard off a disk and detaches it, implementing the
// RoseStorage remove flow (StartRemove -> DrainStep* -> FinishJob). It runs the
// whole job under a durable `job` row so a crash mid-drain resumes from the
// shards still on the disk rather than restarting or stranding the disk
// half-drained. The disk is moved to draining immediately (so placement stops
// targeting it) and to detached only once it holds nothing, honoring the spec's
// NoDetachedData invariant.
//
// Each shard is relocated with the same copy-then-repoint discipline as
// compaction: the plog file is copied to the destination disk and made durable,
// then the placement metadata is atomically flipped, then the source file is
// removed. A crash before the flip leaves the old copy authoritative; a crash
// after it leaves only a stray file on a disk that is being removed anyway.
func (s *Server) DrainDisk(ctx context.Context, diskID uint32) error {
	s.vlogMu.Lock()
	defer s.vlogMu.Unlock()

	if _, ok := s.diskRoots[diskID]; !ok {
		return fmt.Errorf("drain: disk %d is not configured", diskID)
	}
	switch s.diskState[diskID] {
	case meta.DiskActive, meta.DiskDraining: // startable, or resuming a started drain
	default:
		return fmt.Errorf("drain: disk %d is %s, cannot drain", diskID, s.diskState[diskID])
	}

	job, err := s.db.GetOrCreateDrainJob(ctx, diskID)
	if err != nil {
		return err
	}
	if s.diskState[diskID] != meta.DiskDraining {
		if err := s.setDiskStateLocked(ctx, diskID, meta.DiskDraining); err != nil {
			return err
		}
	}

	plogs, err := s.db.PlogsOnDisk(ctx, diskID)
	if err != nil {
		return err
	}
	for _, p := range plogs {
		dest, err := s.pickDrainDestinationLocked(ctx, p.VlogID, diskID)
		if err != nil {
			return err
		}
		if err := s.migratePlogLocked(ctx, p.PlogID, p.VlogID, diskID, dest); err != nil {
			return err
		}
	}

	if err := s.setDiskStateLocked(ctx, diskID, meta.DiskDetached); err != nil {
		return err
	}
	return s.db.MarkJobDone(ctx, job.ID)
}

// ReprotectDisk regenerates every shard lost with a failed disk onto healthy
// disks, restoring the redundancy the failure took away. It implements the
// RoseStorage reprotect flow (StartReprotect -> ReprotectStep* -> FinishJob)
// under a durable `job` row keyed by the failed disk, so a crash mid-reprotect
// resumes from the shards still mapped to the failed disk's plogs.
//
// Unlike drain, the failed disk's bytes are gone: each shard is rebuilt from the
// surviving redundancy (a sibling copy for DUPLICATE, a reed-solomon reconstruct
// for EC) rather than copied off the disk. The regenerated bytes are made durable
// in a fresh plog on a placement-allowed disk before the shard mapping is
// atomically flipped (ReplaceShardPlog), so a crash before the flip leaves the
// shard referencing the failed disk and the step re-runs. The disk stays failed
// afterward: reprotect restores durability, it does not repair hardware.
func (s *Server) ReprotectDisk(ctx context.Context, diskID uint32) error {
	s.vlogMu.Lock()
	defer s.vlogMu.Unlock()

	if _, ok := s.diskRoots[diskID]; !ok {
		return fmt.Errorf("reprotect: disk %d is not configured", diskID)
	}
	if s.diskState[diskID] != meta.DiskFailed {
		return fmt.Errorf("reprotect: disk %d is %s, only failed disks are reprotected", diskID, s.diskState[diskID])
	}

	job, err := s.db.GetOrCreateReprotectJob(ctx, diskID)
	if err != nil {
		return err
	}

	plogs, err := s.db.PlogsOnDisk(ctx, diskID)
	if err != nil {
		return err
	}
	for _, p := range plogs {
		dest, err := s.pickDrainDestinationLocked(ctx, p.VlogID, diskID)
		if err != nil {
			return err
		}
		if err := s.regenerateShardLocked(ctx, p.VlogID, p.ShardIndex, p.PlogID, dest); err != nil {
			return err
		}
	}

	return s.db.MarkJobDone(ctx, job.ID)
}

// regenerateShardLocked rebuilds one shard lost on a failed disk and repoints the
// vlog at the regenerated plog. The lost shard's bytes are reconstructed from the
// surviving redundancy, written durably to a fresh plog on toDisk, then the shard
// mapping is atomically flipped and the owning vlog re-mounted. The caller must
// hold vlogMu.
func (s *Server) regenerateShardLocked(ctx context.Context, vlogID uint32, shardIdx int, lostPlogID, toDisk uint32) error {
	info, err := s.db.GetVlog(ctx, vlogID)
	if err != nil {
		return err
	}

	var shardData []byte
	switch info.ProtectionScheme {
	case "DUPLICATE":
		shardData, err = s.readSurvivingCopyLocked(vlogID, lostPlogID)
	case "EC":
		shardData, err = s.reconstructECShardLocked(ctx, info, shardIdx, lostPlogID)
	default:
		return fmt.Errorf("reprotect: vlog %d scheme %s has no redundancy to regenerate from (data lost)", vlogID, info.ProtectionScheme)
	}
	if err != nil {
		return err
	}

	// Make the regenerated bytes durable in a fresh plog before flipping the
	// shard mapping, so a crash before the flip leaves the old (lost) mapping and
	// the step re-runs rather than exposing a half-written shard.
	newPlogID, err := s.db.MakePlog(ctx, toDisk)
	if err != nil {
		return err
	}
	np, err := storage.OpenPlog(s.plogPath(toDisk, newPlogID), newPlogID)
	if err != nil {
		return fmt.Errorf("reprotect: open regenerated plog %d on disk %d: %w", newPlogID, toDisk, err)
	}
	if _, err := np.Write(0, shardData); err != nil {
		return fmt.Errorf("reprotect: write regenerated shard to plog %d: %w", newPlogID, err)
	}
	if err := np.Commit(); err != nil {
		return fmt.Errorf("reprotect: commit regenerated plog %d: %w", newPlogID, err)
	}
	s.plogs[newPlogID] = np

	if err := s.db.ReplaceShardPlog(ctx, vlogID, shardIdx, lostPlogID, newPlogID); err != nil {
		return err
	}
	delete(s.plogs, lostPlogID)

	if s.activeVlog == vlogID {
		s.activeVlog = 0
	}
	return s.remountVlogLocked(ctx, vlogID)
}

// readSurvivingCopyLocked returns the full logical bytes of any surviving mirror
// of a DUPLICATE vlog other than the lost copy, healing bitrot in passing (the
// read verifies sector hashes). The caller must hold vlogMu.
func (s *Server) readSurvivingCopyLocked(vlogID, lostPlogID uint32) ([]byte, error) {
	mappings, err := s.db.ListVlogPlogs(context.Background(), vlogID)
	if err != nil {
		return nil, err
	}
	for _, m := range mappings {
		if m.PlogID == lostPlogID {
			continue
		}
		p, ok := s.plogs[m.PlogID]
		if !ok {
			continue
		}
		return p.Read(0, int(p.LogicalLength()))
	}
	return nil, fmt.Errorf("reprotect: vlog %d has no surviving copy to regenerate from (data lost)", vlogID)
}

// reconstructECShardLocked rebuilds one EC shard's full byte stream from the
// surviving data and parity shards. Every shard plog holds an equal-length
// stream (each write contributes equal-size pieces to every shard), so a single
// reconstruct over the full length recovers the lost shard element-wise. The
// caller must hold vlogMu.
func (s *Server) reconstructECShardLocked(ctx context.Context, info meta.VlogInfo, lostShard int, lostPlogID uint32) ([]byte, error) {
	mappings, err := s.db.ListVlogPlogs(ctx, info.ID)
	if err != nil {
		return nil, err
	}
	total := int(info.DataShards + info.ParityShards)
	shards := make([][]byte, total)
	present := 0
	for _, m := range mappings {
		if m.PlogID == lostPlogID || m.ShardIndex == lostShard {
			continue // the shard we are regenerating: leave nil
		}
		p, ok := s.plogs[m.PlogID]
		if !ok {
			continue // another shard also lost: leave nil for reconstruct
		}
		data, err := p.Read(0, int(p.LogicalLength()))
		if err != nil {
			return nil, fmt.Errorf("reprotect: read surviving shard %d of vlog %d: %w", m.ShardIndex, info.ID, err)
		}
		shards[m.ShardIndex] = data
		present++
	}
	if present < int(info.DataShards) {
		return nil, fmt.Errorf("reprotect: vlog %d has %d surviving shards, need %d to reconstruct (data lost)", info.ID, present, info.DataShards)
	}
	if err := storage.ReconstructECShard(int(info.DataShards), int(info.ParityShards), shards); err != nil {
		return nil, fmt.Errorf("reprotect: reconstruct vlog %d shard %d: %w", info.ID, lostShard, err)
	}
	return shards[lostShard], nil
}

// AttachDisk configures a new local disk and registers it active in the durable
// catalog, making it eligible for placement and as a replace destination. It is
// the operator action that brings fresh capacity online. (AddDisk is reserved by
// the gRPC surface for the future RPC driver.)
func (s *Server) AttachDisk(ctx context.Context, diskID uint32, root string) error {
	s.vlogMu.Lock()
	defer s.vlogMu.Unlock()
	if _, ok := s.diskRoots[diskID]; ok {
		return fmt.Errorf("attach disk: disk %d already configured", diskID)
	}
	if err := s.db.RegisterDisk(ctx, diskID, diskID); err != nil {
		return err
	}
	s.diskRoots[diskID] = root
	s.diskState[diskID] = meta.DiskActive
	return nil
}

// ReplaceDisk evacuates every shard off oldDisk onto a freshly added newDisk and
// detaches oldDisk, implementing the RoseStorage replace flow (ReplaceDisk ->
// DrainStep* onto the pinned destination -> FinishJob). It is drain with the
// destination pinned: rather than scattering shards across whatever active disks
// have room, every shard lands on the one new disk, the swap-in-place an operator
// expects when retiring a disk for a replacement.
//
// It runs under a durable `job` row (kind=replace, target_disk=old,
// dest_disk=new) so a crash mid-replace resumes onto the same destination from
// the shards still on the old disk. Each shard is relocated with the same
// copy-then-repoint discipline as drain. (ReplaceDisk is reserved by the gRPC
// surface for the future RPC driver.)
func (s *Server) ReplaceDiskWith(ctx context.Context, oldDisk, newDisk uint32) error {
	s.vlogMu.Lock()
	defer s.vlogMu.Unlock()

	if _, ok := s.diskRoots[oldDisk]; !ok {
		return fmt.Errorf("replace: disk %d is not configured", oldDisk)
	}
	if _, ok := s.diskRoots[newDisk]; !ok {
		return fmt.Errorf("replace: destination disk %d is not configured (add it first)", newDisk)
	}
	if oldDisk == newDisk {
		return fmt.Errorf("replace: source and destination are the same disk %d", oldDisk)
	}
	switch s.diskState[oldDisk] {
	case meta.DiskActive, meta.DiskDraining: // startable, or resuming a started replace
	default:
		return fmt.Errorf("replace: disk %d is %s, cannot replace", oldDisk, s.diskState[oldDisk])
	}
	if s.diskState[newDisk] != meta.DiskActive {
		return fmt.Errorf("replace: destination disk %d is %s, must be active", newDisk, s.diskState[newDisk])
	}

	job, err := s.db.GetOrCreateReplaceJob(ctx, oldDisk, newDisk)
	if err != nil {
		return err
	}
	newDisk = job.DestDisk // honor a resumed job's pinned destination over the argument
	if s.diskState[oldDisk] != meta.DiskDraining {
		if err := s.setDiskStateLocked(ctx, oldDisk, meta.DiskDraining); err != nil {
			return err
		}
	}

	plogs, err := s.db.PlogsOnDisk(ctx, oldDisk)
	if err != nil {
		return err
	}
	for _, p := range plogs {
		if err := s.ensurePlacementAllowedLocked(ctx, p.VlogID, newDisk); err != nil {
			return err
		}
		if err := s.migratePlogLocked(ctx, p.PlogID, p.VlogID, oldDisk, newDisk); err != nil {
			return err
		}
	}

	if err := s.setDiskStateLocked(ctx, oldDisk, meta.DiskDetached); err != nil {
		return err
	}
	return s.db.MarkJobDone(ctx, job.ID)
}

// ensurePlacementAllowedLocked verifies a vlog has no shard already on toDisk, so
// relocating a shard there does not collapse two shards/copies onto one disk
// (PlacementAllowed). The caller must hold vlogMu.
func (s *Server) ensurePlacementAllowedLocked(ctx context.Context, vlogID, toDisk uint32) error {
	shards, err := s.db.VlogShardDisks(ctx, vlogID)
	if err != nil {
		return err
	}
	for _, sh := range shards {
		if sh.DiskID == toDisk {
			return fmt.Errorf("replace: disk %d already holds a shard of vlog %d, would collapse redundancy", toDisk, vlogID)
		}
	}
	return nil
}

// Rebalance evens shard counts across active disks, implementing the RoseStorage
// RebalanceStep as a bounded, best-effort pass. It moves shards off the busiest
// disks onto the idlest, but only while the spread exceeds the hysteresis band
// and only up to the per-pass move cap, and it skips entirely inside the cooldown
// window after a prior pass moved something. It returns how many shards it moved.
//
// Unlike drain/reprotect/replace, rebalance has no must-finish obligation: every
// move is individually crash-safe (copy-then-repoint via migratePlogLocked) and a
// partially completed pass leaves a valid, merely-less-even cluster that the next
// pass continues from. So it carries no durable job row to resume.
func (s *Server) Rebalance(ctx context.Context) (int, error) {
	s.vlogMu.Lock()
	defer s.vlogMu.Unlock()

	pol := s.rebalance
	if pol.Cooldown > 0 && !s.lastRebalance.IsZero() && time.Since(s.lastRebalance) < pol.Cooldown {
		return 0, nil // within the backoff window: leave the minor imbalance alone
	}

	active := s.activeDiskIDs()
	if len(active) < 2 {
		return 0, nil
	}

	counts := make(map[uint32]int, len(active))
	plogsByDisk := make(map[uint32][]meta.PlogOnDisk, len(active))
	for _, d := range active {
		ps, err := s.db.PlogsOnDisk(ctx, d)
		if err != nil {
			return 0, err
		}
		counts[d] = len(ps)
		plogsByDisk[d] = ps
	}

	moves := 0
	for pol.MaxMovesPerPass <= 0 || moves < pol.MaxMovesPerPass {
		src, dst := diskExtremes(active, counts)
		if counts[src]-counts[dst] <= pol.MinSkew {
			break // spread is within the hysteresis band; minor imbalance is fine
		}
		moved, err := s.rebalanceOneLocked(ctx, src, pol.MinSkew, counts, plogsByDisk)
		if err != nil {
			return moves, err
		}
		if !moved {
			break // nothing on the busiest disk can legally move to a lighter one
		}
		moves++
	}
	if moves > 0 {
		s.lastRebalance = time.Now()
	}
	return moves, nil
}

// diskExtremes returns the busiest and idlest disk by shard count, scanning in
// the (sorted) active order so ties break deterministically.
func diskExtremes(active []uint32, counts map[uint32]int) (busiest, idlest uint32) {
	busiest, idlest = active[0], active[0]
	for _, d := range active {
		if counts[d] > counts[busiest] {
			busiest = d
		}
		if counts[d] < counts[idlest] {
			idlest = d
		}
	}
	return busiest, idlest
}

// rebalanceOneLocked relocates a single shard off src onto the lightest active
// disk that does not already hold a shard of the same vlog (PlacementAllowed) and
// is at least minSkew+1 shards lighter than src, so the move actually improves
// balance beyond the hysteresis band. It updates counts and plogsByDisk in place
// and reports whether it moved anything. The caller must hold vlogMu.
func (s *Server) rebalanceOneLocked(ctx context.Context, src uint32, minSkew int, counts map[uint32]int, plogsByDisk map[uint32][]meta.PlogOnDisk) (bool, error) {
	for _, p := range plogsByDisk[src] {
		shards, err := s.db.VlogShardDisks(ctx, p.VlogID)
		if err != nil {
			return false, err
		}
		occupied := make(map[uint32]bool, len(shards))
		for _, sh := range shards {
			occupied[sh.DiskID] = true
		}

		dst, dstCount := uint32(0), -1
		for d, c := range counts {
			if d == src || occupied[d] {
				continue
			}
			if dstCount == -1 || c < dstCount {
				dst, dstCount = d, c
			}
		}
		if dstCount == -1 || counts[src]-dstCount <= minSkew {
			continue // no legal destination, or moving there would not help
		}

		if err := s.migratePlogLocked(ctx, p.PlogID, p.VlogID, src, dst); err != nil {
			return false, err
		}
		counts[src]--
		counts[dst]++
		plogsByDisk[src] = removePlog(plogsByDisk[src], p.PlogID)
		plogsByDisk[dst] = append(plogsByDisk[dst], p)
		return true, nil
	}
	return false, nil
}

func removePlog(plogs []meta.PlogOnDisk, plogID uint32) []meta.PlogOnDisk {
	for i, p := range plogs {
		if p.PlogID == plogID {
			return append(plogs[:i], plogs[i+1:]...)
		}
	}
	return plogs
}

// setDiskStateLocked persists a disk transition and updates the cache. The
// caller must hold vlogMu.
func (s *Server) setDiskStateLocked(ctx context.Context, diskID uint32, state string) error {
	if err := s.db.SetDiskState(ctx, diskID, state); err != nil {
		return err
	}
	s.diskState[diskID] = state
	return nil
}

// pickDrainDestinationLocked selects an active disk that can legally host a
// shard of vlogID being moved off fromDisk. It enforces PlacementAllowed: the
// destination must not already hold another shard (EC) or copy (DUPLICATE) of
// the same vlog, so a relocation never collapses two shards onto one disk. The
// caller must hold vlogMu.
func (s *Server) pickDrainDestinationLocked(ctx context.Context, vlogID, fromDisk uint32) (uint32, error) {
	shards, err := s.db.VlogShardDisks(ctx, vlogID)
	if err != nil {
		return 0, err
	}
	occupied := make(map[uint32]bool, len(shards))
	for _, sh := range shards {
		occupied[sh.DiskID] = true
	}
	for _, id := range s.activeDiskIDs() { // active disks only; excludes fromDisk (now draining)
		if id == fromDisk || occupied[id] {
			continue
		}
		return id, nil
	}
	return 0, fmt.Errorf("drain: no placement-allowed destination for vlog %d shard (need an active disk not already holding a shard)", vlogID)
}

// migratePlogLocked relocates one plog's bytes from fromDisk to toDisk and
// repoints its placement, then re-mounts the owning vlog so in-memory clients
// resolve to the relocated file. The caller must hold vlogMu.
func (s *Server) migratePlogLocked(ctx context.Context, plogID, vlogID, fromDisk, toDisk uint32) error {
	oldPath := s.plogPath(fromDisk, plogID)
	newPath := s.plogPath(toDisk, plogID)

	// Flush and close the live handle so we copy a consistent, durable file.
	if p, ok := s.plogs[plogID]; ok {
		if err := p.Commit(); err != nil {
			return fmt.Errorf("drain: flush plog %d: %w", plogID, err)
		}
		_ = p.Close()
	}
	if err := copyFile(oldPath, newPath); err != nil {
		return fmt.Errorf("drain: copy plog %d to disk %d: %w", plogID, toDisk, err)
	}
	// Until this commits, the source copy remains authoritative.
	if err := s.db.MovePlogToDisk(ctx, plogID, toDisk); err != nil {
		return err
	}
	_ = os.Remove(oldPath)

	reopened, err := storage.OpenPlog(newPath, plogID)
	if err != nil {
		return fmt.Errorf("drain: reopen plog %d on disk %d: %w", plogID, toDisk, err)
	}
	s.plogs[plogID] = reopened

	// The active vlog must not stay pinned to a relocated shard mid-write; force
	// a fresh active vlog for subsequent writes, as compaction does.
	if s.activeVlog == vlogID {
		s.activeVlog = 0
	}
	return s.remountVlogLocked(ctx, vlogID)
}

// remountVlogLocked rebuilds a vlog's in-memory client set from current
// placement metadata, used after a shard's backing plog moves. The caller must
// hold vlogMu.
func (s *Server) remountVlogLocked(ctx context.Context, vlogID uint32) error {
	info, err := s.db.GetVlog(ctx, vlogID)
	if err != nil {
		return err
	}
	mappings, err := s.db.ListVlogPlogs(ctx, vlogID)
	if err != nil {
		return err
	}
	clients := make([]storage.PlogClient, len(mappings))
	for i, m := range mappings {
		if m.ShardIndex != i {
			return fmt.Errorf("vlog %d has non-contiguous shard mapping", vlogID)
		}
		plog, ok := s.plogs[m.PlogID]
		if !ok {
			return fmt.Errorf("vlog %d references missing plog %d", vlogID, m.PlogID)
		}
		clients[i] = &localPlogClient{plog: plog}
	}
	vlog, err := storage.NewVlog(info.ID, info.ProtectionScheme, int(info.DataShards), int(info.ParityShards), clients, info.Length)
	if err != nil {
		return fmt.Errorf("remount vlog %d: %w", vlogID, err)
	}
	s.vlogs[vlogID] = vlog
	return nil
}

// copyFile copies src to dst verbatim and fsyncs it. Plog files are byte-exact
// (fixed sectors, interposed hash sectors), so a verbatim copy preserves every
// logical offset the placement metadata already points at.
func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0o644)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	if err := out.Sync(); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}
