// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: proto/format.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlogHeader is the protobuf payload of a plog's on-disk superblock (sector 0).
// It makes a plog self-describing: its own identity, the cluster it belongs to,
// the disk it lives on, and its vlog membership at creation time. UIDs are the
// stable, collision-resistant identifiers; the small monotonic *_id fields are
// runtime conveniences that can collide across wiped/recreated clusters. The
// membership fields reflect the layout at creation; the metadata DB remains
// authoritative for live placement.
type PlogHeader struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClusterUid     []byte                 `protobuf:"bytes,1,opt,name=cluster_uid,json=clusterUid,proto3" json:"cluster_uid,omitempty"`                // 15 bytes, from the SQLite cluster record
	PlogUid        []byte                 `protobuf:"bytes,2,opt,name=plog_uid,json=plogUid,proto3" json:"plog_uid,omitempty"`                         // 15 bytes, this plog's UID
	PlogId         uint32                 `protobuf:"varint,3,opt,name=plog_id,json=plogId,proto3" json:"plog_id,omitempty"`                           // small monotonic int, runtime mapping
	DiskUid        []byte                 `protobuf:"bytes,4,opt,name=disk_uid,json=diskUid,proto3" json:"disk_uid,omitempty"`                         // 15 bytes, identifies the physical disk
	DiskId         uint32                 `protobuf:"varint,14,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`                          // small int, config-relative
	CreatedAtNanos int64                  `protobuf:"varint,5,opt,name=created_at_nanos,json=createdAtNanos,proto3" json:"created_at_nanos,omitempty"` // unix nanos at creation
	WriterVersion  string                 `protobuf:"bytes,6,opt,name=writer_version,json=writerVersion,proto3" json:"writer_version,omitempty"`       // software/build identifier (best-effort)
	// Vlog membership ("vlog header") captured at creation.
	VlogUid          []byte `protobuf:"bytes,7,opt,name=vlog_uid,json=vlogUid,proto3" json:"vlog_uid,omitempty"` // 15 bytes, owning vlog's UID
	VlogId           uint32 `protobuf:"varint,8,opt,name=vlog_id,json=vlogId,proto3" json:"vlog_id,omitempty"`
	ShardIndex       uint32 `protobuf:"varint,9,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`
	ProtectionScheme string `protobuf:"bytes,10,opt,name=protection_scheme,json=protectionScheme,proto3" json:"protection_scheme,omitempty"` // NONE | DUPLICATE | EC
	DataShards       uint32 `protobuf:"varint,11,opt,name=data_shards,json=dataShards,proto3" json:"data_shards,omitempty"`
	ParityShards     uint32 `protobuf:"varint,12,opt,name=parity_shards,json=parityShards,proto3" json:"parity_shards,omitempty"`
	// Indexed by shard_index; each entry is a 15-byte plog UID.
	SiblingPlogUids [][]byte `protobuf:"bytes,13,rep,name=sibling_plog_uids,json=siblingPlogUids,proto3" json:"sibling_plog_uids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlogHeader) Reset() {
	*x = PlogHeader{}
	mi := &file_proto_format_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlogHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlogHeader) ProtoMessage() {}

func (x *PlogHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_format_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlogHeader.ProtoReflect.Descriptor instead.
func (*PlogHeader) Descriptor() ([]byte, []int) {
	return file_proto_format_proto_rawDescGZIP(), []int{0}
}

func (x *PlogHeader) GetClusterUid() []byte {
	if x != nil {
		return x.ClusterUid
	}
	return nil
}

func (x *PlogHeader) GetPlogUid() []byte {
	if x != nil {
		return x.PlogUid
	}
	return nil
}

func (x *PlogHeader) GetPlogId() uint32 {
	if x != nil {
		return x.PlogId
	}
	return 0
}

func (x *PlogHeader) GetDiskUid() []byte {
	if x != nil {
		return x.DiskUid
	}
	return nil
}

func (x *PlogHeader) GetDiskId() uint32 {
	if x != nil {
		return x.DiskId
	}
	return 0
}

func (x *PlogHeader) GetCreatedAtNanos() int64 {
	if x != nil {
		return x.CreatedAtNanos
	}
	return 0
}

func (x *PlogHeader) GetWriterVersion() string {
	if x != nil {
		return x.WriterVersion
	}
	return ""
}

func (x *PlogHeader) GetVlogUid() []byte {
	if x != nil {
		return x.VlogUid
	}
	return nil
}

func (x *PlogHeader) GetVlogId() uint32 {
	if x != nil {
		return x.VlogId
	}
	return 0
}

func (x *PlogHeader) GetShardIndex() uint32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

func (x *PlogHeader) GetProtectionScheme() string {
	if x != nil {
		return x.ProtectionScheme
	}
	return ""
}

func (x *PlogHeader) GetDataShards() uint32 {
	if x != nil {
		return x.DataShards
	}
	return 0
}

func (x *PlogHeader) GetParityShards() uint32 {
	if x != nil {
		return x.ParityShards
	}
	return 0
}

func (x *PlogHeader) GetSiblingPlogUids() [][]byte {
	if x != nil {
		return x.SiblingPlogUids
	}
	return nil
}

var File_proto_format_proto protoreflect.FileDescriptor

const file_proto_format_proto_rawDesc = "" +
	"\n" +
	"\x12proto/format.proto\x12\arose.v1\"\xda\x03\n" +
	"\n" +
	"PlogHeader\x12\x1f\n" +
	"\vcluster_uid\x18\x01 \x01(\fR\n" +
	"clusterUid\x12\x19\n" +
	"\bplog_uid\x18\x02 \x01(\fR\aplogUid\x12\x17\n" +
	"\aplog_id\x18\x03 \x01(\rR\x06plogId\x12\x19\n" +
	"\bdisk_uid\x18\x04 \x01(\fR\adiskUid\x12\x17\n" +
	"\adisk_id\x18\x0e \x01(\rR\x06diskId\x12(\n" +
	"\x10created_at_nanos\x18\x05 \x01(\x03R\x0ecreatedAtNanos\x12%\n" +
	"\x0ewriter_version\x18\x06 \x01(\tR\rwriterVersion\x12\x19\n" +
	"\bvlog_uid\x18\a \x01(\fR\avlogUid\x12\x17\n" +
	"\avlog_id\x18\b \x01(\rR\x06vlogId\x12\x1f\n" +
	"\vshard_index\x18\t \x01(\rR\n" +
	"shardIndex\x12+\n" +
	"\x11protection_scheme\x18\n" +
	" \x01(\tR\x10protectionScheme\x12\x1f\n" +
	"\vdata_shards\x18\v \x01(\rR\n" +
	"dataShards\x12#\n" +
	"\rparity_shards\x18\f \x01(\rR\fparityShards\x12*\n" +
	"\x11sibling_plog_uids\x18\r \x03(\fR\x0fsiblingPlogUidsB\x1cZ\x1agithub.com/rmmh/rose/protob\x06proto3"

var (
	file_proto_format_proto_rawDescOnce sync.Once
	file_proto_format_proto_rawDescData []byte
)

func file_proto_format_proto_rawDescGZIP() []byte {
	file_proto_format_proto_rawDescOnce.Do(func() {
		file_proto_format_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_format_proto_rawDesc), len(file_proto_format_proto_rawDesc)))
	})
	return file_proto_format_proto_rawDescData
}

var file_proto_format_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_format_proto_goTypes = []any{
	(*PlogHeader)(nil), // 0: rose.v1.PlogHeader
}
var file_proto_format_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_format_proto_init() }
func file_proto_format_proto_init() {
	if File_proto_format_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_format_proto_rawDesc), len(file_proto_format_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_format_proto_goTypes,
		DependencyIndexes: file_proto_format_proto_depIdxs,
		MessageInfos:      file_proto_format_proto_msgTypes,
	}.Build()
	File_proto_format_proto = out.File
	file_proto_format_proto_goTypes = nil
	file_proto_format_proto_depIdxs = nil
}
