// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0
// source: proto/rose.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rose_Open_FullMethodName              = "/rose.v1.Rose/Open"
	Rose_Write_FullMethodName             = "/rose.v1.Rose/Write"
	Rose_Read_FullMethodName              = "/rose.v1.Rose/Read"
	Rose_Truncate_FullMethodName          = "/rose.v1.Rose/Truncate"
	Rose_Close_FullMethodName             = "/rose.v1.Rose/Close"
	Rose_Getattr_FullMethodName           = "/rose.v1.Rose/Getattr"
	Rose_Setattr_FullMethodName           = "/rose.v1.Rose/Setattr"
	Rose_Unlink_FullMethodName            = "/rose.v1.Rose/Unlink"
	Rose_Rename_FullMethodName            = "/rose.v1.Rose/Rename"
	Rose_ListDir_FullMethodName           = "/rose.v1.Rose/ListDir"
	Rose_Mkdir_FullMethodName             = "/rose.v1.Rose/Mkdir"
	Rose_Rmdir_FullMethodName             = "/rose.v1.Rose/Rmdir"
	Rose_CreateSnapshot_FullMethodName    = "/rose.v1.Rose/CreateSnapshot"
	Rose_DeleteSnapshot_FullMethodName    = "/rose.v1.Rose/DeleteSnapshot"
	Rose_OpenSnapshot_FullMethodName      = "/rose.v1.Rose/OpenSnapshot"
	Rose_MakeVlog_FullMethodName          = "/rose.v1.Rose/MakeVlog"
	Rose_WriteVlog_FullMethodName         = "/rose.v1.Rose/WriteVlog"
	Rose_ReadVlog_FullMethodName          = "/rose.v1.Rose/ReadVlog"
	Rose_CommitVlog_FullMethodName        = "/rose.v1.Rose/CommitVlog"
	Rose_MakePlog_FullMethodName          = "/rose.v1.Rose/MakePlog"
	Rose_WritePlog_FullMethodName         = "/rose.v1.Rose/WritePlog"
	Rose_ReadPlog_FullMethodName          = "/rose.v1.Rose/ReadPlog"
	Rose_CommitPlog_FullMethodName        = "/rose.v1.Rose/CommitPlog"
	Rose_AddDisk_FullMethodName           = "/rose.v1.Rose/AddDisk"
	Rose_RemoveDisk_FullMethodName        = "/rose.v1.Rose/RemoveDisk"
	Rose_ReplaceDisk_FullMethodName       = "/rose.v1.Rose/ReplaceDisk"
	Rose_StartReprotect_FullMethodName    = "/rose.v1.Rose/StartReprotect"
	Rose_StartRebalance_FullMethodName    = "/rose.v1.Rose/StartRebalance"
	Rose_GetMaintenanceJob_FullMethodName = "/rose.v1.Rose/GetMaintenanceJob"
)

// RoseClient is the client API for Rose service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoseClient interface {
	// File operations
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*TruncateResponse, error)
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	Getattr(ctx context.Context, in *GetattrRequest, opts ...grpc.CallOption) (*GetattrResponse, error)
	Setattr(ctx context.Context, in *SetattrRequest, opts ...grpc.CallOption) (*SetattrResponse, error)
	Unlink(ctx context.Context, in *UnlinkRequest, opts ...grpc.CallOption) (*UnlinkResponse, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error)
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
	Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error)
	Rmdir(ctx context.Context, in *RmdirRequest, opts ...grpc.CallOption) (*RmdirResponse, error)
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	OpenSnapshot(ctx context.Context, in *OpenSnapshotRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	// Virtual Log operations
	MakeVlog(ctx context.Context, in *MakeVlogRequest, opts ...grpc.CallOption) (*MakeVlogResponse, error)
	WriteVlog(ctx context.Context, in *WriteVlogRequest, opts ...grpc.CallOption) (*WriteVlogResponse, error)
	ReadVlog(ctx context.Context, in *ReadVlogRequest, opts ...grpc.CallOption) (*ReadVlogResponse, error)
	CommitVlog(ctx context.Context, in *CommitVlogRequest, opts ...grpc.CallOption) (*CommitVlogResponse, error)
	// Physical Log operations
	MakePlog(ctx context.Context, in *MakePlogRequest, opts ...grpc.CallOption) (*MakePlogResponse, error)
	WritePlog(ctx context.Context, in *WritePlogRequest, opts ...grpc.CallOption) (*WritePlogResponse, error)
	ReadPlog(ctx context.Context, in *ReadPlogRequest, opts ...grpc.CallOption) (*ReadPlogResponse, error)
	CommitPlog(ctx context.Context, in *CommitPlogRequest, opts ...grpc.CallOption) (*CommitPlogResponse, error)
	// Disk management operations. Long-running operations return a job that
	// reports progress while data movement continues concurrently with I/O.
	AddDisk(ctx context.Context, in *AddDiskRequest, opts ...grpc.CallOption) (*AddDiskResponse, error)
	RemoveDisk(ctx context.Context, in *RemoveDiskRequest, opts ...grpc.CallOption) (*MaintenanceJobResponse, error)
	ReplaceDisk(ctx context.Context, in *ReplaceDiskRequest, opts ...grpc.CallOption) (*MaintenanceJobResponse, error)
	StartReprotect(ctx context.Context, in *StartReprotectRequest, opts ...grpc.CallOption) (*MaintenanceJobResponse, error)
	StartRebalance(ctx context.Context, in *StartRebalanceRequest, opts ...grpc.CallOption) (*MaintenanceJobResponse, error)
	GetMaintenanceJob(ctx context.Context, in *GetMaintenanceJobRequest, opts ...grpc.CallOption) (*GetMaintenanceJobResponse, error)
}

type roseClient struct {
	cc grpc.ClientConnInterface
}

func NewRoseClient(cc grpc.ClientConnInterface) RoseClient {
	return &roseClient{cc}
}

func (c *roseClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, Rose_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, Rose_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, Rose_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*TruncateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TruncateResponse)
	err := c.cc.Invoke(ctx, Rose_Truncate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, Rose_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Getattr(ctx context.Context, in *GetattrRequest, opts ...grpc.CallOption) (*GetattrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetattrResponse)
	err := c.cc.Invoke(ctx, Rose_Getattr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Setattr(ctx context.Context, in *SetattrRequest, opts ...grpc.CallOption) (*SetattrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetattrResponse)
	err := c.cc.Invoke(ctx, Rose_Setattr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Unlink(ctx context.Context, in *UnlinkRequest, opts ...grpc.CallOption) (*UnlinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlinkResponse)
	err := c.cc.Invoke(ctx, Rose_Unlink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameResponse)
	err := c.cc.Invoke(ctx, Rose_Rename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, Rose_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MkdirResponse)
	err := c.cc.Invoke(ctx, Rose_Mkdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Rmdir(ctx context.Context, in *RmdirRequest, opts ...grpc.CallOption) (*RmdirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RmdirResponse)
	err := c.cc.Invoke(ctx, Rose_Rmdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, Rose_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, Rose_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) OpenSnapshot(ctx context.Context, in *OpenSnapshotRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, Rose_OpenSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) MakeVlog(ctx context.Context, in *MakeVlogRequest, opts ...grpc.CallOption) (*MakeVlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeVlogResponse)
	err := c.cc.Invoke(ctx, Rose_MakeVlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) WriteVlog(ctx context.Context, in *WriteVlogRequest, opts ...grpc.CallOption) (*WriteVlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteVlogResponse)
	err := c.cc.Invoke(ctx, Rose_WriteVlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) ReadVlog(ctx context.Context, in *ReadVlogRequest, opts ...grpc.CallOption) (*ReadVlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadVlogResponse)
	err := c.cc.Invoke(ctx, Rose_ReadVlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) CommitVlog(ctx context.Context, in *CommitVlogRequest, opts ...grpc.CallOption) (*CommitVlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitVlogResponse)
	err := c.cc.Invoke(ctx, Rose_CommitVlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) MakePlog(ctx context.Context, in *MakePlogRequest, opts ...grpc.CallOption) (*MakePlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakePlogResponse)
	err := c.cc.Invoke(ctx, Rose_MakePlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) WritePlog(ctx context.Context, in *WritePlogRequest, opts ...grpc.CallOption) (*WritePlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WritePlogResponse)
	err := c.cc.Invoke(ctx, Rose_WritePlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) ReadPlog(ctx context.Context, in *ReadPlogRequest, opts ...grpc.CallOption) (*ReadPlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadPlogResponse)
	err := c.cc.Invoke(ctx, Rose_ReadPlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) CommitPlog(ctx context.Context, in *CommitPlogRequest, opts ...grpc.CallOption) (*CommitPlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitPlogResponse)
	err := c.cc.Invoke(ctx, Rose_CommitPlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) AddDisk(ctx context.Context, in *AddDiskRequest, opts ...grpc.CallOption) (*AddDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDiskResponse)
	err := c.cc.Invoke(ctx, Rose_AddDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) RemoveDisk(ctx context.Context, in *RemoveDiskRequest, opts ...grpc.CallOption) (*MaintenanceJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaintenanceJobResponse)
	err := c.cc.Invoke(ctx, Rose_RemoveDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) ReplaceDisk(ctx context.Context, in *ReplaceDiskRequest, opts ...grpc.CallOption) (*MaintenanceJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaintenanceJobResponse)
	err := c.cc.Invoke(ctx, Rose_ReplaceDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) StartReprotect(ctx context.Context, in *StartReprotectRequest, opts ...grpc.CallOption) (*MaintenanceJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaintenanceJobResponse)
	err := c.cc.Invoke(ctx, Rose_StartReprotect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) StartRebalance(ctx context.Context, in *StartRebalanceRequest, opts ...grpc.CallOption) (*MaintenanceJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaintenanceJobResponse)
	err := c.cc.Invoke(ctx, Rose_StartRebalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) GetMaintenanceJob(ctx context.Context, in *GetMaintenanceJobRequest, opts ...grpc.CallOption) (*GetMaintenanceJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMaintenanceJobResponse)
	err := c.cc.Invoke(ctx, Rose_GetMaintenanceJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoseServer is the server API for Rose service.
// All implementations must embed UnimplementedRoseServer
// for forward compatibility.
type RoseServer interface {
	// File operations
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Truncate(context.Context, *TruncateRequest) (*TruncateResponse, error)
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	Getattr(context.Context, *GetattrRequest) (*GetattrResponse, error)
	Setattr(context.Context, *SetattrRequest) (*SetattrResponse, error)
	Unlink(context.Context, *UnlinkRequest) (*UnlinkResponse, error)
	Rename(context.Context, *RenameRequest) (*RenameResponse, error)
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	Mkdir(context.Context, *MkdirRequest) (*MkdirResponse, error)
	Rmdir(context.Context, *RmdirRequest) (*RmdirResponse, error)
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	OpenSnapshot(context.Context, *OpenSnapshotRequest) (*OpenResponse, error)
	// Virtual Log operations
	MakeVlog(context.Context, *MakeVlogRequest) (*MakeVlogResponse, error)
	WriteVlog(context.Context, *WriteVlogRequest) (*WriteVlogResponse, error)
	ReadVlog(context.Context, *ReadVlogRequest) (*ReadVlogResponse, error)
	CommitVlog(context.Context, *CommitVlogRequest) (*CommitVlogResponse, error)
	// Physical Log operations
	MakePlog(context.Context, *MakePlogRequest) (*MakePlogResponse, error)
	WritePlog(context.Context, *WritePlogRequest) (*WritePlogResponse, error)
	ReadPlog(context.Context, *ReadPlogRequest) (*ReadPlogResponse, error)
	CommitPlog(context.Context, *CommitPlogRequest) (*CommitPlogResponse, error)
	// Disk management operations. Long-running operations return a job that
	// reports progress while data movement continues concurrently with I/O.
	AddDisk(context.Context, *AddDiskRequest) (*AddDiskResponse, error)
	RemoveDisk(context.Context, *RemoveDiskRequest) (*MaintenanceJobResponse, error)
	ReplaceDisk(context.Context, *ReplaceDiskRequest) (*MaintenanceJobResponse, error)
	StartReprotect(context.Context, *StartReprotectRequest) (*MaintenanceJobResponse, error)
	StartRebalance(context.Context, *StartRebalanceRequest) (*MaintenanceJobResponse, error)
	GetMaintenanceJob(context.Context, *GetMaintenanceJobRequest) (*GetMaintenanceJobResponse, error)
	mustEmbedUnimplementedRoseServer()
}

// UnimplementedRoseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoseServer struct{}

func (UnimplementedRoseServer) Open(context.Context, *OpenRequest) (*OpenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedRoseServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedRoseServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedRoseServer) Truncate(context.Context, *TruncateRequest) (*TruncateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Truncate not implemented")
}
func (UnimplementedRoseServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedRoseServer) Getattr(context.Context, *GetattrRequest) (*GetattrResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Getattr not implemented")
}
func (UnimplementedRoseServer) Setattr(context.Context, *SetattrRequest) (*SetattrResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Setattr not implemented")
}
func (UnimplementedRoseServer) Unlink(context.Context, *UnlinkRequest) (*UnlinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unlink not implemented")
}
func (UnimplementedRoseServer) Rename(context.Context, *RenameRequest) (*RenameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedRoseServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedRoseServer) Mkdir(context.Context, *MkdirRequest) (*MkdirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mkdir not implemented")
}
func (UnimplementedRoseServer) Rmdir(context.Context, *RmdirRequest) (*RmdirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rmdir not implemented")
}
func (UnimplementedRoseServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedRoseServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedRoseServer) OpenSnapshot(context.Context, *OpenSnapshotRequest) (*OpenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenSnapshot not implemented")
}
func (UnimplementedRoseServer) MakeVlog(context.Context, *MakeVlogRequest) (*MakeVlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeVlog not implemented")
}
func (UnimplementedRoseServer) WriteVlog(context.Context, *WriteVlogRequest) (*WriteVlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteVlog not implemented")
}
func (UnimplementedRoseServer) ReadVlog(context.Context, *ReadVlogRequest) (*ReadVlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadVlog not implemented")
}
func (UnimplementedRoseServer) CommitVlog(context.Context, *CommitVlogRequest) (*CommitVlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitVlog not implemented")
}
func (UnimplementedRoseServer) MakePlog(context.Context, *MakePlogRequest) (*MakePlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakePlog not implemented")
}
func (UnimplementedRoseServer) WritePlog(context.Context, *WritePlogRequest) (*WritePlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WritePlog not implemented")
}
func (UnimplementedRoseServer) ReadPlog(context.Context, *ReadPlogRequest) (*ReadPlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadPlog not implemented")
}
func (UnimplementedRoseServer) CommitPlog(context.Context, *CommitPlogRequest) (*CommitPlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitPlog not implemented")
}
func (UnimplementedRoseServer) AddDisk(context.Context, *AddDiskRequest) (*AddDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDisk not implemented")
}
func (UnimplementedRoseServer) RemoveDisk(context.Context, *RemoveDiskRequest) (*MaintenanceJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDisk not implemented")
}
func (UnimplementedRoseServer) ReplaceDisk(context.Context, *ReplaceDiskRequest) (*MaintenanceJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaceDisk not implemented")
}
func (UnimplementedRoseServer) StartReprotect(context.Context, *StartReprotectRequest) (*MaintenanceJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartReprotect not implemented")
}
func (UnimplementedRoseServer) StartRebalance(context.Context, *StartRebalanceRequest) (*MaintenanceJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRebalance not implemented")
}
func (UnimplementedRoseServer) GetMaintenanceJob(context.Context, *GetMaintenanceJobRequest) (*GetMaintenanceJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMaintenanceJob not implemented")
}
func (UnimplementedRoseServer) mustEmbedUnimplementedRoseServer() {}
func (UnimplementedRoseServer) testEmbeddedByValue()              {}

// UnsafeRoseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoseServer will
// result in compilation errors.
type UnsafeRoseServer interface {
	mustEmbedUnimplementedRoseServer()
}

func RegisterRoseServer(s grpc.ServiceRegistrar, srv RoseServer) {
	// If the following call panics, it indicates UnimplementedRoseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rose_ServiceDesc, srv)
}

func _Rose_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Truncate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TruncateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Truncate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Truncate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Truncate(ctx, req.(*TruncateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Getattr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetattrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Getattr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Getattr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Getattr(ctx, req.(*GetattrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Setattr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetattrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Setattr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Setattr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Setattr(ctx, req.(*SetattrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Unlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Unlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Unlink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Unlink(ctx, req.(*UnlinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Rename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Mkdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Mkdir(ctx, req.(*MkdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Rmdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RmdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Rmdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Rmdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Rmdir(ctx, req.(*RmdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_OpenSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).OpenSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_OpenSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).OpenSnapshot(ctx, req.(*OpenSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_MakeVlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeVlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).MakeVlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_MakeVlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).MakeVlog(ctx, req.(*MakeVlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_WriteVlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteVlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).WriteVlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_WriteVlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).WriteVlog(ctx, req.(*WriteVlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_ReadVlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadVlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).ReadVlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_ReadVlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).ReadVlog(ctx, req.(*ReadVlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_CommitVlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitVlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).CommitVlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_CommitVlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).CommitVlog(ctx, req.(*CommitVlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_MakePlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakePlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).MakePlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_MakePlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).MakePlog(ctx, req.(*MakePlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_WritePlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WritePlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).WritePlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_WritePlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).WritePlog(ctx, req.(*WritePlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_ReadPlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).ReadPlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_ReadPlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).ReadPlog(ctx, req.(*ReadPlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_CommitPlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitPlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).CommitPlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_CommitPlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).CommitPlog(ctx, req.(*CommitPlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_AddDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).AddDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_AddDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).AddDisk(ctx, req.(*AddDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_RemoveDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).RemoveDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_RemoveDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).RemoveDisk(ctx, req.(*RemoveDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_ReplaceDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).ReplaceDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_ReplaceDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).ReplaceDisk(ctx, req.(*ReplaceDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_StartReprotect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartReprotectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).StartReprotect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_StartReprotect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).StartReprotect(ctx, req.(*StartReprotectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_StartRebalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRebalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).StartRebalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_StartRebalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).StartRebalance(ctx, req.(*StartRebalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_GetMaintenanceJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMaintenanceJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).GetMaintenanceJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_GetMaintenanceJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).GetMaintenanceJob(ctx, req.(*GetMaintenanceJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rose_ServiceDesc is the grpc.ServiceDesc for Rose service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rose_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rose.v1.Rose",
	HandlerType: (*RoseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _Rose_Open_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Rose_Write_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Rose_Read_Handler,
		},
		{
			MethodName: "Truncate",
			Handler:    _Rose_Truncate_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Rose_Close_Handler,
		},
		{
			MethodName: "Getattr",
			Handler:    _Rose_Getattr_Handler,
		},
		{
			MethodName: "Setattr",
			Handler:    _Rose_Setattr_Handler,
		},
		{
			MethodName: "Unlink",
			Handler:    _Rose_Unlink_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _Rose_Rename_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _Rose_ListDir_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _Rose_Mkdir_Handler,
		},
		{
			MethodName: "Rmdir",
			Handler:    _Rose_Rmdir_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _Rose_CreateSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _Rose_DeleteSnapshot_Handler,
		},
		{
			MethodName: "OpenSnapshot",
			Handler:    _Rose_OpenSnapshot_Handler,
		},
		{
			MethodName: "MakeVlog",
			Handler:    _Rose_MakeVlog_Handler,
		},
		{
			MethodName: "WriteVlog",
			Handler:    _Rose_WriteVlog_Handler,
		},
		{
			MethodName: "ReadVlog",
			Handler:    _Rose_ReadVlog_Handler,
		},
		{
			MethodName: "CommitVlog",
			Handler:    _Rose_CommitVlog_Handler,
		},
		{
			MethodName: "MakePlog",
			Handler:    _Rose_MakePlog_Handler,
		},
		{
			MethodName: "WritePlog",
			Handler:    _Rose_WritePlog_Handler,
		},
		{
			MethodName: "ReadPlog",
			Handler:    _Rose_ReadPlog_Handler,
		},
		{
			MethodName: "CommitPlog",
			Handler:    _Rose_CommitPlog_Handler,
		},
		{
			MethodName: "AddDisk",
			Handler:    _Rose_AddDisk_Handler,
		},
		{
			MethodName: "RemoveDisk",
			Handler:    _Rose_RemoveDisk_Handler,
		},
		{
			MethodName: "ReplaceDisk",
			Handler:    _Rose_ReplaceDisk_Handler,
		},
		{
			MethodName: "StartReprotect",
			Handler:    _Rose_StartReprotect_Handler,
		},
		{
			MethodName: "StartRebalance",
			Handler:    _Rose_StartRebalance_Handler,
		},
		{
			MethodName: "GetMaintenanceJob",
			Handler:    _Rose_GetMaintenanceJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rose.proto",
}
