// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/rose.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rose_Open_FullMethodName       = "/rose.v1.Rose/Open"
	Rose_Write_FullMethodName      = "/rose.v1.Rose/Write"
	Rose_Read_FullMethodName       = "/rose.v1.Rose/Read"
	Rose_Close_FullMethodName      = "/rose.v1.Rose/Close"
	Rose_Getattr_FullMethodName    = "/rose.v1.Rose/Getattr"
	Rose_MakeVlog_FullMethodName   = "/rose.v1.Rose/MakeVlog"
	Rose_WriteVlog_FullMethodName  = "/rose.v1.Rose/WriteVlog"
	Rose_ReadVlog_FullMethodName   = "/rose.v1.Rose/ReadVlog"
	Rose_CommitVlog_FullMethodName = "/rose.v1.Rose/CommitVlog"
	Rose_MakePlog_FullMethodName   = "/rose.v1.Rose/MakePlog"
	Rose_WritePlog_FullMethodName  = "/rose.v1.Rose/WritePlog"
	Rose_ReadPlog_FullMethodName   = "/rose.v1.Rose/ReadPlog"
	Rose_CommitPlog_FullMethodName = "/rose.v1.Rose/CommitPlog"
)

// RoseClient is the client API for Rose service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoseClient interface {
	// File operations
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	Getattr(ctx context.Context, in *GetattrRequest, opts ...grpc.CallOption) (*GetattrResponse, error)
	// Virtual Log operations
	MakeVlog(ctx context.Context, in *MakeVlogRequest, opts ...grpc.CallOption) (*MakeVlogResponse, error)
	WriteVlog(ctx context.Context, in *WriteVlogRequest, opts ...grpc.CallOption) (*WriteVlogResponse, error)
	ReadVlog(ctx context.Context, in *ReadVlogRequest, opts ...grpc.CallOption) (*ReadVlogResponse, error)
	CommitVlog(ctx context.Context, in *CommitVlogRequest, opts ...grpc.CallOption) (*CommitVlogResponse, error)
	// Physical Log operations
	MakePlog(ctx context.Context, in *MakePlogRequest, opts ...grpc.CallOption) (*MakePlogResponse, error)
	WritePlog(ctx context.Context, in *WritePlogRequest, opts ...grpc.CallOption) (*WritePlogResponse, error)
	ReadPlog(ctx context.Context, in *ReadPlogRequest, opts ...grpc.CallOption) (*ReadPlogResponse, error)
	CommitPlog(ctx context.Context, in *CommitPlogRequest, opts ...grpc.CallOption) (*CommitPlogResponse, error)
}

type roseClient struct {
	cc grpc.ClientConnInterface
}

func NewRoseClient(cc grpc.ClientConnInterface) RoseClient {
	return &roseClient{cc}
}

func (c *roseClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, Rose_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, Rose_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, Rose_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, Rose_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) Getattr(ctx context.Context, in *GetattrRequest, opts ...grpc.CallOption) (*GetattrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetattrResponse)
	err := c.cc.Invoke(ctx, Rose_Getattr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) MakeVlog(ctx context.Context, in *MakeVlogRequest, opts ...grpc.CallOption) (*MakeVlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeVlogResponse)
	err := c.cc.Invoke(ctx, Rose_MakeVlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) WriteVlog(ctx context.Context, in *WriteVlogRequest, opts ...grpc.CallOption) (*WriteVlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteVlogResponse)
	err := c.cc.Invoke(ctx, Rose_WriteVlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) ReadVlog(ctx context.Context, in *ReadVlogRequest, opts ...grpc.CallOption) (*ReadVlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadVlogResponse)
	err := c.cc.Invoke(ctx, Rose_ReadVlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) CommitVlog(ctx context.Context, in *CommitVlogRequest, opts ...grpc.CallOption) (*CommitVlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitVlogResponse)
	err := c.cc.Invoke(ctx, Rose_CommitVlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) MakePlog(ctx context.Context, in *MakePlogRequest, opts ...grpc.CallOption) (*MakePlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakePlogResponse)
	err := c.cc.Invoke(ctx, Rose_MakePlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) WritePlog(ctx context.Context, in *WritePlogRequest, opts ...grpc.CallOption) (*WritePlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WritePlogResponse)
	err := c.cc.Invoke(ctx, Rose_WritePlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) ReadPlog(ctx context.Context, in *ReadPlogRequest, opts ...grpc.CallOption) (*ReadPlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadPlogResponse)
	err := c.cc.Invoke(ctx, Rose_ReadPlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roseClient) CommitPlog(ctx context.Context, in *CommitPlogRequest, opts ...grpc.CallOption) (*CommitPlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitPlogResponse)
	err := c.cc.Invoke(ctx, Rose_CommitPlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoseServer is the server API for Rose service.
// All implementations must embed UnimplementedRoseServer
// for forward compatibility.
type RoseServer interface {
	// File operations
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	Getattr(context.Context, *GetattrRequest) (*GetattrResponse, error)
	// Virtual Log operations
	MakeVlog(context.Context, *MakeVlogRequest) (*MakeVlogResponse, error)
	WriteVlog(context.Context, *WriteVlogRequest) (*WriteVlogResponse, error)
	ReadVlog(context.Context, *ReadVlogRequest) (*ReadVlogResponse, error)
	CommitVlog(context.Context, *CommitVlogRequest) (*CommitVlogResponse, error)
	// Physical Log operations
	MakePlog(context.Context, *MakePlogRequest) (*MakePlogResponse, error)
	WritePlog(context.Context, *WritePlogRequest) (*WritePlogResponse, error)
	ReadPlog(context.Context, *ReadPlogRequest) (*ReadPlogResponse, error)
	CommitPlog(context.Context, *CommitPlogRequest) (*CommitPlogResponse, error)
	mustEmbedUnimplementedRoseServer()
}

// UnimplementedRoseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoseServer struct{}

func (UnimplementedRoseServer) Open(context.Context, *OpenRequest) (*OpenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedRoseServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedRoseServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedRoseServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedRoseServer) Getattr(context.Context, *GetattrRequest) (*GetattrResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Getattr not implemented")
}
func (UnimplementedRoseServer) MakeVlog(context.Context, *MakeVlogRequest) (*MakeVlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeVlog not implemented")
}
func (UnimplementedRoseServer) WriteVlog(context.Context, *WriteVlogRequest) (*WriteVlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteVlog not implemented")
}
func (UnimplementedRoseServer) ReadVlog(context.Context, *ReadVlogRequest) (*ReadVlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadVlog not implemented")
}
func (UnimplementedRoseServer) CommitVlog(context.Context, *CommitVlogRequest) (*CommitVlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitVlog not implemented")
}
func (UnimplementedRoseServer) MakePlog(context.Context, *MakePlogRequest) (*MakePlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakePlog not implemented")
}
func (UnimplementedRoseServer) WritePlog(context.Context, *WritePlogRequest) (*WritePlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WritePlog not implemented")
}
func (UnimplementedRoseServer) ReadPlog(context.Context, *ReadPlogRequest) (*ReadPlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadPlog not implemented")
}
func (UnimplementedRoseServer) CommitPlog(context.Context, *CommitPlogRequest) (*CommitPlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitPlog not implemented")
}
func (UnimplementedRoseServer) mustEmbedUnimplementedRoseServer() {}
func (UnimplementedRoseServer) testEmbeddedByValue()              {}

// UnsafeRoseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoseServer will
// result in compilation errors.
type UnsafeRoseServer interface {
	mustEmbedUnimplementedRoseServer()
}

func RegisterRoseServer(s grpc.ServiceRegistrar, srv RoseServer) {
	// If the following call panics, it indicates UnimplementedRoseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rose_ServiceDesc, srv)
}

func _Rose_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_Getattr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetattrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).Getattr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_Getattr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).Getattr(ctx, req.(*GetattrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_MakeVlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeVlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).MakeVlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_MakeVlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).MakeVlog(ctx, req.(*MakeVlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_WriteVlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteVlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).WriteVlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_WriteVlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).WriteVlog(ctx, req.(*WriteVlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_ReadVlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadVlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).ReadVlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_ReadVlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).ReadVlog(ctx, req.(*ReadVlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_CommitVlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitVlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).CommitVlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_CommitVlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).CommitVlog(ctx, req.(*CommitVlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_MakePlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakePlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).MakePlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_MakePlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).MakePlog(ctx, req.(*MakePlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_WritePlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WritePlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).WritePlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_WritePlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).WritePlog(ctx, req.(*WritePlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_ReadPlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).ReadPlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_ReadPlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).ReadPlog(ctx, req.(*ReadPlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rose_CommitPlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitPlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoseServer).CommitPlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rose_CommitPlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoseServer).CommitPlog(ctx, req.(*CommitPlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rose_ServiceDesc is the grpc.ServiceDesc for Rose service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rose_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rose.v1.Rose",
	HandlerType: (*RoseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _Rose_Open_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Rose_Write_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Rose_Read_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Rose_Close_Handler,
		},
		{
			MethodName: "Getattr",
			Handler:    _Rose_Getattr_Handler,
		},
		{
			MethodName: "MakeVlog",
			Handler:    _Rose_MakeVlog_Handler,
		},
		{
			MethodName: "WriteVlog",
			Handler:    _Rose_WriteVlog_Handler,
		},
		{
			MethodName: "ReadVlog",
			Handler:    _Rose_ReadVlog_Handler,
		},
		{
			MethodName: "CommitVlog",
			Handler:    _Rose_CommitVlog_Handler,
		},
		{
			MethodName: "MakePlog",
			Handler:    _Rose_MakePlog_Handler,
		},
		{
			MethodName: "WritePlog",
			Handler:    _Rose_WritePlog_Handler,
		},
		{
			MethodName: "ReadPlog",
			Handler:    _Rose_ReadPlog_Handler,
		},
		{
			MethodName: "CommitPlog",
			Handler:    _Rose_CommitPlog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rose.proto",
}
