// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: proto/rose.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaintenanceJobState int32

const (
	MaintenanceJobState_MAINTENANCE_JOB_STATE_UNSPECIFIED MaintenanceJobState = 0
	MaintenanceJobState_MAINTENANCE_JOB_STATE_RUNNING     MaintenanceJobState = 1
	MaintenanceJobState_MAINTENANCE_JOB_STATE_COMPLETED   MaintenanceJobState = 2
	MaintenanceJobState_MAINTENANCE_JOB_STATE_FAILED      MaintenanceJobState = 3
)

// Enum value maps for MaintenanceJobState.
var (
	MaintenanceJobState_name = map[int32]string{
		0: "MAINTENANCE_JOB_STATE_UNSPECIFIED",
		1: "MAINTENANCE_JOB_STATE_RUNNING",
		2: "MAINTENANCE_JOB_STATE_COMPLETED",
		3: "MAINTENANCE_JOB_STATE_FAILED",
	}
	MaintenanceJobState_value = map[string]int32{
		"MAINTENANCE_JOB_STATE_UNSPECIFIED": 0,
		"MAINTENANCE_JOB_STATE_RUNNING":     1,
		"MAINTENANCE_JOB_STATE_COMPLETED":   2,
		"MAINTENANCE_JOB_STATE_FAILED":      3,
	}
)

func (x MaintenanceJobState) Enum() *MaintenanceJobState {
	p := new(MaintenanceJobState)
	*p = x
	return p
}

func (x MaintenanceJobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MaintenanceJobState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rose_proto_enumTypes[0].Descriptor()
}

func (MaintenanceJobState) Type() protoreflect.EnumType {
	return &file_proto_rose_proto_enumTypes[0]
}

func (x MaintenanceJobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MaintenanceJobState.Descriptor instead.
func (MaintenanceJobState) EnumDescriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{0}
}

// File requests
type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	OperationKey  string                 `protobuf:"bytes,2,opt,name=operation_key,json=operationKey,proto3" json:"operation_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_proto_rose_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{0}
}

func (x *OpenRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OpenRequest) GetOperationKey() string {
	if x != nil {
		return x.OperationKey
	}
	return ""
}

type OpenResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Handle             int64                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	AcknowledgedOffset int64                  `protobuf:"varint,2,opt,name=acknowledged_offset,json=acknowledgedOffset,proto3" json:"acknowledged_offset,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_proto_rose_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{1}
}

func (x *OpenResponse) GetHandle() int64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *OpenResponse) GetAcknowledgedOffset() int64 {
	if x != nil {
		return x.AcknowledgedOffset
	}
	return 0
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        int64                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,2,opt,name=buffer,proto3" json:"buffer,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_rose_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRequest) GetHandle() int64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *WriteRequest) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *WriteRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type WriteResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AcknowledgedOffset int64                  `protobuf:"varint,1,opt,name=acknowledged_offset,json=acknowledgedOffset,proto3" json:"acknowledged_offset,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_rose_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{3}
}

func (x *WriteResponse) GetAcknowledgedOffset() int64 {
	if x != nil {
		return x.AcknowledgedOffset
	}
	return 0
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        int64                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_rose_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRequest) GetHandle() int64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *ReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffer        []byte                 `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_rose_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{5}
}

func (x *ReadResponse) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type TruncateRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Handle int64                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// path is used when no open write handle is supplied (a truncate(2) by path).
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	OperationKey  string `protobuf:"bytes,3,opt,name=operation_key,json=operationKey,proto3" json:"operation_key,omitempty"`
	Size          int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateRequest) Reset() {
	*x = TruncateRequest{}
	mi := &file_proto_rose_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateRequest) ProtoMessage() {}

func (x *TruncateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateRequest.ProtoReflect.Descriptor instead.
func (*TruncateRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{6}
}

func (x *TruncateRequest) GetHandle() int64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *TruncateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TruncateRequest) GetOperationKey() string {
	if x != nil {
		return x.OperationKey
	}
	return ""
}

func (x *TruncateRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type TruncateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateResponse) Reset() {
	*x = TruncateResponse{}
	mi := &file_proto_rose_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateResponse) ProtoMessage() {}

func (x *TruncateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateResponse.ProtoReflect.Descriptor instead.
func (*TruncateResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{7}
}

type GetattrRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// When non-zero, read the live size from this open write handle's cache so a
	// stat between write and close reflects the uncommitted length.
	Handle        int64 `protobuf:"varint,2,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetattrRequest) Reset() {
	*x = GetattrRequest{}
	mi := &file_proto_rose_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetattrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetattrRequest) ProtoMessage() {}

func (x *GetattrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetattrRequest.ProtoReflect.Descriptor instead.
func (*GetattrRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{8}
}

func (x *GetattrRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetattrRequest) GetHandle() int64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

type GetattrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Mtime         int64                  `protobuf:"varint,3,opt,name=mtime,proto3" json:"mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetattrResponse) Reset() {
	*x = GetattrResponse{}
	mi := &file_proto_rose_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetattrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetattrResponse) ProtoMessage() {}

func (x *GetattrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetattrResponse.ProtoReflect.Descriptor instead.
func (*GetattrResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{9}
}

func (x *GetattrResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetattrResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *GetattrResponse) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

type UnlinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkRequest) Reset() {
	*x = UnlinkRequest{}
	mi := &file_proto_rose_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkRequest) ProtoMessage() {}

func (x *UnlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkRequest.ProtoReflect.Descriptor instead.
func (*UnlinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{10}
}

func (x *UnlinkRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type UnlinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkResponse) Reset() {
	*x = UnlinkResponse{}
	mi := &file_proto_rose_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkResponse) ProtoMessage() {}

func (x *UnlinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkResponse.ProtoReflect.Descriptor instead.
func (*UnlinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{11}
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_proto_rose_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{12}
}

func (x *RenameRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *RenameRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_proto_rose_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{13}
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mtime         int64                  `protobuf:"varint,4,opt,name=mtime,proto3" json:"mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_proto_rose_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{14}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *DirEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DirEntry) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_proto_rose_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{15}
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_proto_rose_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{16}
}

func (x *ListDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_proto_rose_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{17}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_proto_rose_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{18}
}

type RmdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmdirRequest) Reset() {
	*x = RmdirRequest{}
	mi := &file_proto_rose_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmdirRequest) ProtoMessage() {}

func (x *RmdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmdirRequest.ProtoReflect.Descriptor instead.
func (*RmdirRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{19}
}

func (x *RmdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RmdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmdirResponse) Reset() {
	*x = RmdirResponse{}
	mi := &file_proto_rose_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmdirResponse) ProtoMessage() {}

func (x *RmdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmdirResponse.ProtoReflect.Descriptor instead.
func (*RmdirResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{20}
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_proto_rose_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{21}
}

func (x *CreateSnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    uint64                 `protobuf:"varint,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_proto_rose_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{22}
}

func (x *CreateSnapshotResponse) GetSnapshotId() uint64 {
	if x != nil {
		return x.SnapshotId
	}
	return 0
}

type DeleteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    uint64                 `protobuf:"varint,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_proto_rose_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteSnapshotRequest) GetSnapshotId() uint64 {
	if x != nil {
		return x.SnapshotId
	}
	return 0
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_proto_rose_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{24}
}

type OpenSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    uint64                 `protobuf:"varint,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSnapshotRequest) Reset() {
	*x = OpenSnapshotRequest{}
	mi := &file_proto_rose_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSnapshotRequest) ProtoMessage() {}

func (x *OpenSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSnapshotRequest.ProtoReflect.Descriptor instead.
func (*OpenSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{25}
}

func (x *OpenSnapshotRequest) GetSnapshotId() uint64 {
	if x != nil {
		return x.SnapshotId
	}
	return 0
}

func (x *OpenSnapshotRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CloseRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Handle int64                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// Client-generated, stable across retries.  Repeating Close with the same
	// key returns the outcome of the original write rather than appending again.
	IdempotencyKey string `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_proto_rose_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{26}
}

func (x *CloseRequest) GetHandle() int64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *CloseRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_proto_rose_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{27}
}

// Vlog requests
type MakeVlogRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtectionScheme string                 `protobuf:"bytes,1,opt,name=protection_scheme,json=protectionScheme,proto3" json:"protection_scheme,omitempty"`
	DataShards       int32                  `protobuf:"varint,2,opt,name=data_shards,json=dataShards,proto3" json:"data_shards,omitempty"`
	ParityShards     int32                  `protobuf:"varint,3,opt,name=parity_shards,json=parityShards,proto3" json:"parity_shards,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MakeVlogRequest) Reset() {
	*x = MakeVlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeVlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeVlogRequest) ProtoMessage() {}

func (x *MakeVlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeVlogRequest.ProtoReflect.Descriptor instead.
func (*MakeVlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{28}
}

func (x *MakeVlogRequest) GetProtectionScheme() string {
	if x != nil {
		return x.ProtectionScheme
	}
	return ""
}

func (x *MakeVlogRequest) GetDataShards() int32 {
	if x != nil {
		return x.DataShards
	}
	return 0
}

func (x *MakeVlogRequest) GetParityShards() int32 {
	if x != nil {
		return x.ParityShards
	}
	return 0
}

type MakeVlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VlogId        uint32                 `protobuf:"varint,1,opt,name=vlog_id,json=vlogId,proto3" json:"vlog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeVlogResponse) Reset() {
	*x = MakeVlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeVlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeVlogResponse) ProtoMessage() {}

func (x *MakeVlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeVlogResponse.ProtoReflect.Descriptor instead.
func (*MakeVlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{29}
}

func (x *MakeVlogResponse) GetVlogId() uint32 {
	if x != nil {
		return x.VlogId
	}
	return 0
}

type WriteVlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VlogId        uint32                 `protobuf:"varint,1,opt,name=vlog_id,json=vlogId,proto3" json:"vlog_id,omitempty"`
	TxnId         int64                  `protobuf:"varint,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,3,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteVlogRequest) Reset() {
	*x = WriteVlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteVlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteVlogRequest) ProtoMessage() {}

func (x *WriteVlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteVlogRequest.ProtoReflect.Descriptor instead.
func (*WriteVlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{30}
}

func (x *WriteVlogRequest) GetVlogId() uint32 {
	if x != nil {
		return x.VlogId
	}
	return 0
}

func (x *WriteVlogRequest) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *WriteVlogRequest) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type WriteVlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteVlogResponse) Reset() {
	*x = WriteVlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteVlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteVlogResponse) ProtoMessage() {}

func (x *WriteVlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteVlogResponse.ProtoReflect.Descriptor instead.
func (*WriteVlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{31}
}

func (x *WriteVlogResponse) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadVlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VlogId        uint32                 `protobuf:"varint,1,opt,name=vlog_id,json=vlogId,proto3" json:"vlog_id,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadVlogRequest) Reset() {
	*x = ReadVlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadVlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadVlogRequest) ProtoMessage() {}

func (x *ReadVlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadVlogRequest.ProtoReflect.Descriptor instead.
func (*ReadVlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{32}
}

func (x *ReadVlogRequest) GetVlogId() uint32 {
	if x != nil {
		return x.VlogId
	}
	return 0
}

func (x *ReadVlogRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadVlogRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadVlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffer        []byte                 `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadVlogResponse) Reset() {
	*x = ReadVlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadVlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadVlogResponse) ProtoMessage() {}

func (x *ReadVlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadVlogResponse.ProtoReflect.Descriptor instead.
func (*ReadVlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{33}
}

func (x *ReadVlogResponse) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type CommitVlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         int64                  `protobuf:"varint,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitVlogRequest) Reset() {
	*x = CommitVlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitVlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitVlogRequest) ProtoMessage() {}

func (x *CommitVlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitVlogRequest.ProtoReflect.Descriptor instead.
func (*CommitVlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{34}
}

func (x *CommitVlogRequest) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

type CommitVlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitVlogResponse) Reset() {
	*x = CommitVlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitVlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitVlogResponse) ProtoMessage() {}

func (x *CommitVlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitVlogResponse.ProtoReflect.Descriptor instead.
func (*CommitVlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{35}
}

// Plog requests
type MakePlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        uint32                 `protobuf:"varint,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakePlogRequest) Reset() {
	*x = MakePlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakePlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakePlogRequest) ProtoMessage() {}

func (x *MakePlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakePlogRequest.ProtoReflect.Descriptor instead.
func (*MakePlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{36}
}

func (x *MakePlogRequest) GetDiskId() uint32 {
	if x != nil {
		return x.DiskId
	}
	return 0
}

type MakePlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlogId        uint32                 `protobuf:"varint,1,opt,name=plog_id,json=plogId,proto3" json:"plog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakePlogResponse) Reset() {
	*x = MakePlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakePlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakePlogResponse) ProtoMessage() {}

func (x *MakePlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakePlogResponse.ProtoReflect.Descriptor instead.
func (*MakePlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{37}
}

func (x *MakePlogResponse) GetPlogId() uint32 {
	if x != nil {
		return x.PlogId
	}
	return 0
}

type WritePlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlogId        uint32                 `protobuf:"varint,1,opt,name=plog_id,json=plogId,proto3" json:"plog_id,omitempty"`
	TxnId         int64                  `protobuf:"varint,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	LockId        int64                  `protobuf:"varint,3,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,4,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WritePlogRequest) Reset() {
	*x = WritePlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WritePlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WritePlogRequest) ProtoMessage() {}

func (x *WritePlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WritePlogRequest.ProtoReflect.Descriptor instead.
func (*WritePlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{38}
}

func (x *WritePlogRequest) GetPlogId() uint32 {
	if x != nil {
		return x.PlogId
	}
	return 0
}

func (x *WritePlogRequest) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *WritePlogRequest) GetLockId() int64 {
	if x != nil {
		return x.LockId
	}
	return 0
}

func (x *WritePlogRequest) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type WritePlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WritePlogResponse) Reset() {
	*x = WritePlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WritePlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WritePlogResponse) ProtoMessage() {}

func (x *WritePlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WritePlogResponse.ProtoReflect.Descriptor instead.
func (*WritePlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{39}
}

func (x *WritePlogResponse) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadPlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlogId        uint32                 `protobuf:"varint,1,opt,name=plog_id,json=plogId,proto3" json:"plog_id,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPlogRequest) Reset() {
	*x = ReadPlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPlogRequest) ProtoMessage() {}

func (x *ReadPlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPlogRequest.ProtoReflect.Descriptor instead.
func (*ReadPlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{40}
}

func (x *ReadPlogRequest) GetPlogId() uint32 {
	if x != nil {
		return x.PlogId
	}
	return 0
}

func (x *ReadPlogRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadPlogRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadPlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffer        []byte                 `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPlogResponse) Reset() {
	*x = ReadPlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPlogResponse) ProtoMessage() {}

func (x *ReadPlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPlogResponse.ProtoReflect.Descriptor instead.
func (*ReadPlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{41}
}

func (x *ReadPlogResponse) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type CommitPlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         int64                  `protobuf:"varint,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPlogRequest) Reset() {
	*x = CommitPlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPlogRequest) ProtoMessage() {}

func (x *CommitPlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPlogRequest.ProtoReflect.Descriptor instead.
func (*CommitPlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{42}
}

func (x *CommitPlogRequest) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

type CommitPlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPlogResponse) Reset() {
	*x = CommitPlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPlogResponse) ProtoMessage() {}

func (x *CommitPlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPlogResponse.ProtoReflect.Descriptor instead.
func (*CommitPlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{43}
}

// Disk management requests
type AddDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        uint32                 `protobuf:"varint,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	NodeId        uint32                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDiskRequest) Reset() {
	*x = AddDiskRequest{}
	mi := &file_proto_rose_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDiskRequest) ProtoMessage() {}

func (x *AddDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDiskRequest.ProtoReflect.Descriptor instead.
func (*AddDiskRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{44}
}

func (x *AddDiskRequest) GetDiskId() uint32 {
	if x != nil {
		return x.DiskId
	}
	return 0
}

func (x *AddDiskRequest) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *AddDiskRequest) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type AddDiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDiskResponse) Reset() {
	*x = AddDiskResponse{}
	mi := &file_proto_rose_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDiskResponse) ProtoMessage() {}

func (x *AddDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDiskResponse.ProtoReflect.Descriptor instead.
func (*AddDiskResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{45}
}

type RemoveDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        uint32                 `protobuf:"varint,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDiskRequest) Reset() {
	*x = RemoveDiskRequest{}
	mi := &file_proto_rose_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDiskRequest) ProtoMessage() {}

func (x *RemoveDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDiskRequest.ProtoReflect.Descriptor instead.
func (*RemoveDiskRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{46}
}

func (x *RemoveDiskRequest) GetDiskId() uint32 {
	if x != nil {
		return x.DiskId
	}
	return 0
}

type ReplaceDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldDiskId     uint32                 `protobuf:"varint,1,opt,name=old_disk_id,json=oldDiskId,proto3" json:"old_disk_id,omitempty"`
	NewDiskId     uint32                 `protobuf:"varint,2,opt,name=new_disk_id,json=newDiskId,proto3" json:"new_disk_id,omitempty"`
	NodeId        uint32                 `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceDiskRequest) Reset() {
	*x = ReplaceDiskRequest{}
	mi := &file_proto_rose_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceDiskRequest) ProtoMessage() {}

func (x *ReplaceDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceDiskRequest.ProtoReflect.Descriptor instead.
func (*ReplaceDiskRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{47}
}

func (x *ReplaceDiskRequest) GetOldDiskId() uint32 {
	if x != nil {
		return x.OldDiskId
	}
	return 0
}

func (x *ReplaceDiskRequest) GetNewDiskId() uint32 {
	if x != nil {
		return x.NewDiskId
	}
	return 0
}

func (x *ReplaceDiskRequest) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ReplaceDiskRequest) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type StartReprotectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        uint32                 `protobuf:"varint,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReprotectRequest) Reset() {
	*x = StartReprotectRequest{}
	mi := &file_proto_rose_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReprotectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReprotectRequest) ProtoMessage() {}

func (x *StartReprotectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReprotectRequest.ProtoReflect.Descriptor instead.
func (*StartReprotectRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{48}
}

func (x *StartReprotectRequest) GetDiskId() uint32 {
	if x != nil {
		return x.DiskId
	}
	return 0
}

type StartRebalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRebalanceRequest) Reset() {
	*x = StartRebalanceRequest{}
	mi := &file_proto_rose_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRebalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRebalanceRequest) ProtoMessage() {}

func (x *StartRebalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRebalanceRequest.ProtoReflect.Descriptor instead.
func (*StartRebalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{49}
}

type MaintenanceJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceJobResponse) Reset() {
	*x = MaintenanceJobResponse{}
	mi := &file_proto_rose_proto_msgTypes[50]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceJobResponse) ProtoMessage() {}

func (x *MaintenanceJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[50]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceJobResponse.ProtoReflect.Descriptor instead.
func (*MaintenanceJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{50}
}

func (x *MaintenanceJobResponse) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetMaintenanceJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaintenanceJobRequest) Reset() {
	*x = GetMaintenanceJobRequest{}
	mi := &file_proto_rose_proto_msgTypes[51]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaintenanceJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaintenanceJobRequest) ProtoMessage() {}

func (x *GetMaintenanceJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[51]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaintenanceJobRequest.ProtoReflect.Descriptor instead.
func (*GetMaintenanceJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{51}
}

func (x *GetMaintenanceJobRequest) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetMaintenanceJobResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State          MaintenanceJobState    `protobuf:"varint,2,opt,name=state,proto3,enum=rose.v1.MaintenanceJobState" json:"state,omitempty"`
	CompletedBytes uint64                 `protobuf:"varint,3,opt,name=completed_bytes,json=completedBytes,proto3" json:"completed_bytes,omitempty"`
	TotalBytes     uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMaintenanceJobResponse) Reset() {
	*x = GetMaintenanceJobResponse{}
	mi := &file_proto_rose_proto_msgTypes[52]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaintenanceJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaintenanceJobResponse) ProtoMessage() {}

func (x *GetMaintenanceJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[52]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaintenanceJobResponse.ProtoReflect.Descriptor instead.
func (*GetMaintenanceJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{52}
}

func (x *GetMaintenanceJobResponse) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *GetMaintenanceJobResponse) GetState() MaintenanceJobState {
	if x != nil {
		return x.State
	}
	return MaintenanceJobState_MAINTENANCE_JOB_STATE_UNSPECIFIED
}

func (x *GetMaintenanceJobResponse) GetCompletedBytes() uint64 {
	if x != nil {
		return x.CompletedBytes
	}
	return 0
}

func (x *GetMaintenanceJobResponse) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

var File_proto_rose_proto protoreflect.FileDescriptor

const file_proto_rose_proto_rawDesc = "" +
	"\n" +
	"\x10proto/rose.proto\x12\arose.v1\"F\n" +
	"\vOpenRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\roperation_key\x18\x02 \x01(\tR\foperationKey\"W\n" +
	"\fOpenResponse\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x03R\x06handle\x12/\n" +
	"\x13acknowledged_offset\x18\x02 \x01(\x03R\x12acknowledgedOffset\"V\n" +
	"\fWriteRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x03R\x06handle\x12\x16\n" +
	"\x06buffer\x18\x02 \x01(\fR\x06buffer\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"@\n" +
	"\rWriteResponse\x12/\n" +
	"\x13acknowledged_offset\x18\x01 \x01(\x03R\x12acknowledgedOffset\"U\n" +
	"\vReadRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x03R\x06handle\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"&\n" +
	"\fReadResponse\x12\x16\n" +
	"\x06buffer\x18\x01 \x01(\fR\x06buffer\"v\n" +
	"\x0fTruncateRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x03R\x06handle\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12#\n" +
	"\roperation_key\x18\x03 \x01(\tR\foperationKey\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"\x12\n" +
	"\x10TruncateResponse\"<\n" +
	"\x0eGetattrRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\x03R\x06handle\"R\n" +
	"\x0fGetattrResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x14\n" +
	"\x05mtime\x18\x03 \x01(\x03R\x05mtime\"#\n" +
	"\rUnlinkRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x10\n" +
	"\x0eUnlinkResponse\"E\n" +
	"\rRenameRequest\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\"\x10\n" +
	"\x0eRenameResponse\"_\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x14\n" +
	"\x05mtime\x18\x04 \x01(\x03R\x05mtime\"$\n" +
	"\x0eListDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\">\n" +
	"\x0fListDirResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.rose.v1.DirEntryR\aentries\"\"\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x0f\n" +
	"\rMkdirResponse\"\"\n" +
	"\fRmdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x0f\n" +
	"\rRmdirResponse\"+\n" +
	"\x15CreateSnapshotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"9\n" +
	"\x16CreateSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\x04R\n" +
	"snapshotId\"8\n" +
	"\x15DeleteSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\x04R\n" +
	"snapshotId\"\x18\n" +
	"\x16DeleteSnapshotResponse\"J\n" +
	"\x13OpenSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\x04R\n" +
	"snapshotId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"O\n" +
	"\fCloseRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x03R\x06handle\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"\x0f\n" +
	"\rCloseResponse\"\x84\x01\n" +
	"\x0fMakeVlogRequest\x12+\n" +
	"\x11protection_scheme\x18\x01 \x01(\tR\x10protectionScheme\x12\x1f\n" +
	"\vdata_shards\x18\x02 \x01(\x05R\n" +
	"dataShards\x12#\n" +
	"\rparity_shards\x18\x03 \x01(\x05R\fparityShards\"+\n" +
	"\x10MakeVlogResponse\x12\x17\n" +
	"\avlog_id\x18\x01 \x01(\rR\x06vlogId\"Z\n" +
	"\x10WriteVlogRequest\x12\x17\n" +
	"\avlog_id\x18\x01 \x01(\rR\x06vlogId\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\x03R\x05txnId\x12\x16\n" +
	"\x06buffer\x18\x03 \x01(\fR\x06buffer\"+\n" +
	"\x11WriteVlogResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\"Z\n" +
	"\x0fReadVlogRequest\x12\x17\n" +
	"\avlog_id\x18\x01 \x01(\rR\x06vlogId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\"*\n" +
	"\x10ReadVlogResponse\x12\x16\n" +
	"\x06buffer\x18\x01 \x01(\fR\x06buffer\"*\n" +
	"\x11CommitVlogRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\x03R\x05txnId\"\x14\n" +
	"\x12CommitVlogResponse\"*\n" +
	"\x0fMakePlogRequest\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\rR\x06diskId\"+\n" +
	"\x10MakePlogResponse\x12\x17\n" +
	"\aplog_id\x18\x01 \x01(\rR\x06plogId\"s\n" +
	"\x10WritePlogRequest\x12\x17\n" +
	"\aplog_id\x18\x01 \x01(\rR\x06plogId\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\x03R\x05txnId\x12\x17\n" +
	"\alock_id\x18\x03 \x01(\x03R\x06lockId\x12\x16\n" +
	"\x06buffer\x18\x04 \x01(\fR\x06buffer\"+\n" +
	"\x11WritePlogResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\"Z\n" +
	"\x0fReadPlogRequest\x12\x17\n" +
	"\aplog_id\x18\x01 \x01(\rR\x06plogId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\"*\n" +
	"\x10ReadPlogResponse\x12\x16\n" +
	"\x06buffer\x18\x01 \x01(\fR\x06buffer\"*\n" +
	"\x11CommitPlogRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\x03R\x05txnId\"\x14\n" +
	"\x12CommitPlogResponse\"c\n" +
	"\x0eAddDiskRequest\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\rR\x06diskId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\rR\x06nodeId\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\"\x11\n" +
	"\x0fAddDiskResponse\",\n" +
	"\x11RemoveDiskRequest\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\rR\x06diskId\"\x8e\x01\n" +
	"\x12ReplaceDiskRequest\x12\x1e\n" +
	"\vold_disk_id\x18\x01 \x01(\rR\toldDiskId\x12\x1e\n" +
	"\vnew_disk_id\x18\x02 \x01(\rR\tnewDiskId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\rR\x06nodeId\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\"0\n" +
	"\x15StartReprotectRequest\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\rR\x06diskId\"\x17\n" +
	"\x15StartRebalanceRequest\"/\n" +
	"\x16MaintenanceJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\"1\n" +
	"\x18GetMaintenanceJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\"\xb0\x01\n" +
	"\x19GetMaintenanceJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\x122\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1c.rose.v1.MaintenanceJobStateR\x05state\x12'\n" +
	"\x0fcompleted_bytes\x18\x03 \x01(\x04R\x0ecompletedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes*\xa6\x01\n" +
	"\x13MaintenanceJobState\x12%\n" +
	"!MAINTENANCE_JOB_STATE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dMAINTENANCE_JOB_STATE_RUNNING\x10\x01\x12#\n" +
	"\x1fMAINTENANCE_JOB_STATE_COMPLETED\x10\x02\x12 \n" +
	"\x1cMAINTENANCE_JOB_STATE_FAILED\x10\x032\xe0\x0e\n" +
	"\x04Rose\x123\n" +
	"\x04Open\x12\x14.rose.v1.OpenRequest\x1a\x15.rose.v1.OpenResponse\x126\n" +
	"\x05Write\x12\x15.rose.v1.WriteRequest\x1a\x16.rose.v1.WriteResponse\x123\n" +
	"\x04Read\x12\x14.rose.v1.ReadRequest\x1a\x15.rose.v1.ReadResponse\x12?\n" +
	"\bTruncate\x12\x18.rose.v1.TruncateRequest\x1a\x19.rose.v1.TruncateResponse\x126\n" +
	"\x05Close\x12\x15.rose.v1.CloseRequest\x1a\x16.rose.v1.CloseResponse\x12<\n" +
	"\aGetattr\x12\x17.rose.v1.GetattrRequest\x1a\x18.rose.v1.GetattrResponse\x129\n" +
	"\x06Unlink\x12\x16.rose.v1.UnlinkRequest\x1a\x17.rose.v1.UnlinkResponse\x129\n" +
	"\x06Rename\x12\x16.rose.v1.RenameRequest\x1a\x17.rose.v1.RenameResponse\x12<\n" +
	"\aListDir\x12\x17.rose.v1.ListDirRequest\x1a\x18.rose.v1.ListDirResponse\x126\n" +
	"\x05Mkdir\x12\x15.rose.v1.MkdirRequest\x1a\x16.rose.v1.MkdirResponse\x126\n" +
	"\x05Rmdir\x12\x15.rose.v1.RmdirRequest\x1a\x16.rose.v1.RmdirResponse\x12Q\n" +
	"\x0eCreateSnapshot\x12\x1e.rose.v1.CreateSnapshotRequest\x1a\x1f.rose.v1.CreateSnapshotResponse\x12Q\n" +
	"\x0eDeleteSnapshot\x12\x1e.rose.v1.DeleteSnapshotRequest\x1a\x1f.rose.v1.DeleteSnapshotResponse\x12C\n" +
	"\fOpenSnapshot\x12\x1c.rose.v1.OpenSnapshotRequest\x1a\x15.rose.v1.OpenResponse\x12?\n" +
	"\bMakeVlog\x12\x18.rose.v1.MakeVlogRequest\x1a\x19.rose.v1.MakeVlogResponse\x12B\n" +
	"\tWriteVlog\x12\x19.rose.v1.WriteVlogRequest\x1a\x1a.rose.v1.WriteVlogResponse\x12?\n" +
	"\bReadVlog\x12\x18.rose.v1.ReadVlogRequest\x1a\x19.rose.v1.ReadVlogResponse\x12E\n" +
	"\n" +
	"CommitVlog\x12\x1a.rose.v1.CommitVlogRequest\x1a\x1b.rose.v1.CommitVlogResponse\x12?\n" +
	"\bMakePlog\x12\x18.rose.v1.MakePlogRequest\x1a\x19.rose.v1.MakePlogResponse\x12B\n" +
	"\tWritePlog\x12\x19.rose.v1.WritePlogRequest\x1a\x1a.rose.v1.WritePlogResponse\x12?\n" +
	"\bReadPlog\x12\x18.rose.v1.ReadPlogRequest\x1a\x19.rose.v1.ReadPlogResponse\x12E\n" +
	"\n" +
	"CommitPlog\x12\x1a.rose.v1.CommitPlogRequest\x1a\x1b.rose.v1.CommitPlogResponse\x12<\n" +
	"\aAddDisk\x12\x17.rose.v1.AddDiskRequest\x1a\x18.rose.v1.AddDiskResponse\x12I\n" +
	"\n" +
	"RemoveDisk\x12\x1a.rose.v1.RemoveDiskRequest\x1a\x1f.rose.v1.MaintenanceJobResponse\x12K\n" +
	"\vReplaceDisk\x12\x1b.rose.v1.ReplaceDiskRequest\x1a\x1f.rose.v1.MaintenanceJobResponse\x12Q\n" +
	"\x0eStartReprotect\x12\x1e.rose.v1.StartReprotectRequest\x1a\x1f.rose.v1.MaintenanceJobResponse\x12Q\n" +
	"\x0eStartRebalance\x12\x1e.rose.v1.StartRebalanceRequest\x1a\x1f.rose.v1.MaintenanceJobResponse\x12Z\n" +
	"\x11GetMaintenanceJob\x12!.rose.v1.GetMaintenanceJobRequest\x1a\".rose.v1.GetMaintenanceJobResponseB\x1cZ\x1agithub.com/rmmh/rose/protob\x06proto3"

var (
	file_proto_rose_proto_rawDescOnce sync.Once
	file_proto_rose_proto_rawDescData []byte
)

func file_proto_rose_proto_rawDescGZIP() []byte {
	file_proto_rose_proto_rawDescOnce.Do(func() {
		file_proto_rose_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rose_proto_rawDesc), len(file_proto_rose_proto_rawDesc)))
	})
	return file_proto_rose_proto_rawDescData
}

var file_proto_rose_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_rose_proto_msgTypes = make([]protoimpl.MessageInfo, 53)
var file_proto_rose_proto_goTypes = []any{
	(MaintenanceJobState)(0),          // 0: rose.v1.MaintenanceJobState
	(*OpenRequest)(nil),               // 1: rose.v1.OpenRequest
	(*OpenResponse)(nil),              // 2: rose.v1.OpenResponse
	(*WriteRequest)(nil),              // 3: rose.v1.WriteRequest
	(*WriteResponse)(nil),             // 4: rose.v1.WriteResponse
	(*ReadRequest)(nil),               // 5: rose.v1.ReadRequest
	(*ReadResponse)(nil),              // 6: rose.v1.ReadResponse
	(*TruncateRequest)(nil),           // 7: rose.v1.TruncateRequest
	(*TruncateResponse)(nil),          // 8: rose.v1.TruncateResponse
	(*GetattrRequest)(nil),            // 9: rose.v1.GetattrRequest
	(*GetattrResponse)(nil),           // 10: rose.v1.GetattrResponse
	(*UnlinkRequest)(nil),             // 11: rose.v1.UnlinkRequest
	(*UnlinkResponse)(nil),            // 12: rose.v1.UnlinkResponse
	(*RenameRequest)(nil),             // 13: rose.v1.RenameRequest
	(*RenameResponse)(nil),            // 14: rose.v1.RenameResponse
	(*DirEntry)(nil),                  // 15: rose.v1.DirEntry
	(*ListDirRequest)(nil),            // 16: rose.v1.ListDirRequest
	(*ListDirResponse)(nil),           // 17: rose.v1.ListDirResponse
	(*MkdirRequest)(nil),              // 18: rose.v1.MkdirRequest
	(*MkdirResponse)(nil),             // 19: rose.v1.MkdirResponse
	(*RmdirRequest)(nil),              // 20: rose.v1.RmdirRequest
	(*RmdirResponse)(nil),             // 21: rose.v1.RmdirResponse
	(*CreateSnapshotRequest)(nil),     // 22: rose.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),    // 23: rose.v1.CreateSnapshotResponse
	(*DeleteSnapshotRequest)(nil),     // 24: rose.v1.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil),    // 25: rose.v1.DeleteSnapshotResponse
	(*OpenSnapshotRequest)(nil),       // 26: rose.v1.OpenSnapshotRequest
	(*CloseRequest)(nil),              // 27: rose.v1.CloseRequest
	(*CloseResponse)(nil),             // 28: rose.v1.CloseResponse
	(*MakeVlogRequest)(nil),           // 29: rose.v1.MakeVlogRequest
	(*MakeVlogResponse)(nil),          // 30: rose.v1.MakeVlogResponse
	(*WriteVlogRequest)(nil),          // 31: rose.v1.WriteVlogRequest
	(*WriteVlogResponse)(nil),         // 32: rose.v1.WriteVlogResponse
	(*ReadVlogRequest)(nil),           // 33: rose.v1.ReadVlogRequest
	(*ReadVlogResponse)(nil),          // 34: rose.v1.ReadVlogResponse
	(*CommitVlogRequest)(nil),         // 35: rose.v1.CommitVlogRequest
	(*CommitVlogResponse)(nil),        // 36: rose.v1.CommitVlogResponse
	(*MakePlogRequest)(nil),           // 37: rose.v1.MakePlogRequest
	(*MakePlogResponse)(nil),          // 38: rose.v1.MakePlogResponse
	(*WritePlogRequest)(nil),          // 39: rose.v1.WritePlogRequest
	(*WritePlogResponse)(nil),         // 40: rose.v1.WritePlogResponse
	(*ReadPlogRequest)(nil),           // 41: rose.v1.ReadPlogRequest
	(*ReadPlogResponse)(nil),          // 42: rose.v1.ReadPlogResponse
	(*CommitPlogRequest)(nil),         // 43: rose.v1.CommitPlogRequest
	(*CommitPlogResponse)(nil),        // 44: rose.v1.CommitPlogResponse
	(*AddDiskRequest)(nil),            // 45: rose.v1.AddDiskRequest
	(*AddDiskResponse)(nil),           // 46: rose.v1.AddDiskResponse
	(*RemoveDiskRequest)(nil),         // 47: rose.v1.RemoveDiskRequest
	(*ReplaceDiskRequest)(nil),        // 48: rose.v1.ReplaceDiskRequest
	(*StartReprotectRequest)(nil),     // 49: rose.v1.StartReprotectRequest
	(*StartRebalanceRequest)(nil),     // 50: rose.v1.StartRebalanceRequest
	(*MaintenanceJobResponse)(nil),    // 51: rose.v1.MaintenanceJobResponse
	(*GetMaintenanceJobRequest)(nil),  // 52: rose.v1.GetMaintenanceJobRequest
	(*GetMaintenanceJobResponse)(nil), // 53: rose.v1.GetMaintenanceJobResponse
}
var file_proto_rose_proto_depIdxs = []int32{
	15, // 0: rose.v1.ListDirResponse.entries:type_name -> rose.v1.DirEntry
	0,  // 1: rose.v1.GetMaintenanceJobResponse.state:type_name -> rose.v1.MaintenanceJobState
	1,  // 2: rose.v1.Rose.Open:input_type -> rose.v1.OpenRequest
	3,  // 3: rose.v1.Rose.Write:input_type -> rose.v1.WriteRequest
	5,  // 4: rose.v1.Rose.Read:input_type -> rose.v1.ReadRequest
	7,  // 5: rose.v1.Rose.Truncate:input_type -> rose.v1.TruncateRequest
	27, // 6: rose.v1.Rose.Close:input_type -> rose.v1.CloseRequest
	9,  // 7: rose.v1.Rose.Getattr:input_type -> rose.v1.GetattrRequest
	11, // 8: rose.v1.Rose.Unlink:input_type -> rose.v1.UnlinkRequest
	13, // 9: rose.v1.Rose.Rename:input_type -> rose.v1.RenameRequest
	16, // 10: rose.v1.Rose.ListDir:input_type -> rose.v1.ListDirRequest
	18, // 11: rose.v1.Rose.Mkdir:input_type -> rose.v1.MkdirRequest
	20, // 12: rose.v1.Rose.Rmdir:input_type -> rose.v1.RmdirRequest
	22, // 13: rose.v1.Rose.CreateSnapshot:input_type -> rose.v1.CreateSnapshotRequest
	24, // 14: rose.v1.Rose.DeleteSnapshot:input_type -> rose.v1.DeleteSnapshotRequest
	26, // 15: rose.v1.Rose.OpenSnapshot:input_type -> rose.v1.OpenSnapshotRequest
	29, // 16: rose.v1.Rose.MakeVlog:input_type -> rose.v1.MakeVlogRequest
	31, // 17: rose.v1.Rose.WriteVlog:input_type -> rose.v1.WriteVlogRequest
	33, // 18: rose.v1.Rose.ReadVlog:input_type -> rose.v1.ReadVlogRequest
	35, // 19: rose.v1.Rose.CommitVlog:input_type -> rose.v1.CommitVlogRequest
	37, // 20: rose.v1.Rose.MakePlog:input_type -> rose.v1.MakePlogRequest
	39, // 21: rose.v1.Rose.WritePlog:input_type -> rose.v1.WritePlogRequest
	41, // 22: rose.v1.Rose.ReadPlog:input_type -> rose.v1.ReadPlogRequest
	43, // 23: rose.v1.Rose.CommitPlog:input_type -> rose.v1.CommitPlogRequest
	45, // 24: rose.v1.Rose.AddDisk:input_type -> rose.v1.AddDiskRequest
	47, // 25: rose.v1.Rose.RemoveDisk:input_type -> rose.v1.RemoveDiskRequest
	48, // 26: rose.v1.Rose.ReplaceDisk:input_type -> rose.v1.ReplaceDiskRequest
	49, // 27: rose.v1.Rose.StartReprotect:input_type -> rose.v1.StartReprotectRequest
	50, // 28: rose.v1.Rose.StartRebalance:input_type -> rose.v1.StartRebalanceRequest
	52, // 29: rose.v1.Rose.GetMaintenanceJob:input_type -> rose.v1.GetMaintenanceJobRequest
	2,  // 30: rose.v1.Rose.Open:output_type -> rose.v1.OpenResponse
	4,  // 31: rose.v1.Rose.Write:output_type -> rose.v1.WriteResponse
	6,  // 32: rose.v1.Rose.Read:output_type -> rose.v1.ReadResponse
	8,  // 33: rose.v1.Rose.Truncate:output_type -> rose.v1.TruncateResponse
	28, // 34: rose.v1.Rose.Close:output_type -> rose.v1.CloseResponse
	10, // 35: rose.v1.Rose.Getattr:output_type -> rose.v1.GetattrResponse
	12, // 36: rose.v1.Rose.Unlink:output_type -> rose.v1.UnlinkResponse
	14, // 37: rose.v1.Rose.Rename:output_type -> rose.v1.RenameResponse
	17, // 38: rose.v1.Rose.ListDir:output_type -> rose.v1.ListDirResponse
	19, // 39: rose.v1.Rose.Mkdir:output_type -> rose.v1.MkdirResponse
	21, // 40: rose.v1.Rose.Rmdir:output_type -> rose.v1.RmdirResponse
	23, // 41: rose.v1.Rose.CreateSnapshot:output_type -> rose.v1.CreateSnapshotResponse
	25, // 42: rose.v1.Rose.DeleteSnapshot:output_type -> rose.v1.DeleteSnapshotResponse
	2,  // 43: rose.v1.Rose.OpenSnapshot:output_type -> rose.v1.OpenResponse
	30, // 44: rose.v1.Rose.MakeVlog:output_type -> rose.v1.MakeVlogResponse
	32, // 45: rose.v1.Rose.WriteVlog:output_type -> rose.v1.WriteVlogResponse
	34, // 46: rose.v1.Rose.ReadVlog:output_type -> rose.v1.ReadVlogResponse
	36, // 47: rose.v1.Rose.CommitVlog:output_type -> rose.v1.CommitVlogResponse
	38, // 48: rose.v1.Rose.MakePlog:output_type -> rose.v1.MakePlogResponse
	40, // 49: rose.v1.Rose.WritePlog:output_type -> rose.v1.WritePlogResponse
	42, // 50: rose.v1.Rose.ReadPlog:output_type -> rose.v1.ReadPlogResponse
	44, // 51: rose.v1.Rose.CommitPlog:output_type -> rose.v1.CommitPlogResponse
	46, // 52: rose.v1.Rose.AddDisk:output_type -> rose.v1.AddDiskResponse
	51, // 53: rose.v1.Rose.RemoveDisk:output_type -> rose.v1.MaintenanceJobResponse
	51, // 54: rose.v1.Rose.ReplaceDisk:output_type -> rose.v1.MaintenanceJobResponse
	51, // 55: rose.v1.Rose.StartReprotect:output_type -> rose.v1.MaintenanceJobResponse
	51, // 56: rose.v1.Rose.StartRebalance:output_type -> rose.v1.MaintenanceJobResponse
	53, // 57: rose.v1.Rose.GetMaintenanceJob:output_type -> rose.v1.GetMaintenanceJobResponse
	30, // [30:58] is the sub-list for method output_type
	2,  // [2:30] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_rose_proto_init() }
func file_proto_rose_proto_init() {
	if File_proto_rose_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rose_proto_rawDesc), len(file_proto_rose_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   53,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rose_proto_goTypes,
		DependencyIndexes: file_proto_rose_proto_depIdxs,
		EnumInfos:         file_proto_rose_proto_enumTypes,
		MessageInfos:      file_proto_rose_proto_msgTypes,
	}.Build()
	File_proto_rose_proto = out.File
	file_proto_rose_proto_goTypes = nil
	file_proto_rose_proto_depIdxs = nil
}
