// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/rose.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// File requests
type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_proto_rose_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{0}
}

func (x *OpenRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        int64                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_proto_rose_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{1}
}

func (x *OpenResponse) GetHandle() int64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        int64                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,2,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_rose_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRequest) GetHandle() int64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *WriteRequest) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_rose_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{3}
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        int64                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_rose_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRequest) GetHandle() int64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *ReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffer        []byte                 `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_rose_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{5}
}

func (x *ReadResponse) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type GetattrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetattrRequest) Reset() {
	*x = GetattrRequest{}
	mi := &file_proto_rose_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetattrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetattrRequest) ProtoMessage() {}

func (x *GetattrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetattrRequest.ProtoReflect.Descriptor instead.
func (*GetattrRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{6}
}

func (x *GetattrRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetattrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetattrResponse) Reset() {
	*x = GetattrResponse{}
	mi := &file_proto_rose_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetattrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetattrResponse) ProtoMessage() {}

func (x *GetattrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetattrResponse.ProtoReflect.Descriptor instead.
func (*GetattrResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{7}
}

func (x *GetattrResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        int64                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_proto_rose_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{8}
}

func (x *CloseRequest) GetHandle() int64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_proto_rose_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{9}
}

// Vlog requests
type MakeVlogRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtectionScheme string                 `protobuf:"bytes,1,opt,name=protection_scheme,json=protectionScheme,proto3" json:"protection_scheme,omitempty"`
	DataShards       int32                  `protobuf:"varint,2,opt,name=data_shards,json=dataShards,proto3" json:"data_shards,omitempty"`
	ParityShards     int32                  `protobuf:"varint,3,opt,name=parity_shards,json=parityShards,proto3" json:"parity_shards,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MakeVlogRequest) Reset() {
	*x = MakeVlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeVlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeVlogRequest) ProtoMessage() {}

func (x *MakeVlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeVlogRequest.ProtoReflect.Descriptor instead.
func (*MakeVlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{10}
}

func (x *MakeVlogRequest) GetProtectionScheme() string {
	if x != nil {
		return x.ProtectionScheme
	}
	return ""
}

func (x *MakeVlogRequest) GetDataShards() int32 {
	if x != nil {
		return x.DataShards
	}
	return 0
}

func (x *MakeVlogRequest) GetParityShards() int32 {
	if x != nil {
		return x.ParityShards
	}
	return 0
}

type MakeVlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VlogId        uint32                 `protobuf:"varint,1,opt,name=vlog_id,json=vlogId,proto3" json:"vlog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeVlogResponse) Reset() {
	*x = MakeVlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeVlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeVlogResponse) ProtoMessage() {}

func (x *MakeVlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeVlogResponse.ProtoReflect.Descriptor instead.
func (*MakeVlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{11}
}

func (x *MakeVlogResponse) GetVlogId() uint32 {
	if x != nil {
		return x.VlogId
	}
	return 0
}

type WriteVlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VlogId        uint32                 `protobuf:"varint,1,opt,name=vlog_id,json=vlogId,proto3" json:"vlog_id,omitempty"`
	TxnId         int64                  `protobuf:"varint,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,3,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteVlogRequest) Reset() {
	*x = WriteVlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteVlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteVlogRequest) ProtoMessage() {}

func (x *WriteVlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteVlogRequest.ProtoReflect.Descriptor instead.
func (*WriteVlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{12}
}

func (x *WriteVlogRequest) GetVlogId() uint32 {
	if x != nil {
		return x.VlogId
	}
	return 0
}

func (x *WriteVlogRequest) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *WriteVlogRequest) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type WriteVlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteVlogResponse) Reset() {
	*x = WriteVlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteVlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteVlogResponse) ProtoMessage() {}

func (x *WriteVlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteVlogResponse.ProtoReflect.Descriptor instead.
func (*WriteVlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{13}
}

func (x *WriteVlogResponse) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadVlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VlogId        uint32                 `protobuf:"varint,1,opt,name=vlog_id,json=vlogId,proto3" json:"vlog_id,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadVlogRequest) Reset() {
	*x = ReadVlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadVlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadVlogRequest) ProtoMessage() {}

func (x *ReadVlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadVlogRequest.ProtoReflect.Descriptor instead.
func (*ReadVlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{14}
}

func (x *ReadVlogRequest) GetVlogId() uint32 {
	if x != nil {
		return x.VlogId
	}
	return 0
}

func (x *ReadVlogRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadVlogRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadVlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffer        []byte                 `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadVlogResponse) Reset() {
	*x = ReadVlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadVlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadVlogResponse) ProtoMessage() {}

func (x *ReadVlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadVlogResponse.ProtoReflect.Descriptor instead.
func (*ReadVlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{15}
}

func (x *ReadVlogResponse) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type CommitVlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         int64                  `protobuf:"varint,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitVlogRequest) Reset() {
	*x = CommitVlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitVlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitVlogRequest) ProtoMessage() {}

func (x *CommitVlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitVlogRequest.ProtoReflect.Descriptor instead.
func (*CommitVlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{16}
}

func (x *CommitVlogRequest) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

type CommitVlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitVlogResponse) Reset() {
	*x = CommitVlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitVlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitVlogResponse) ProtoMessage() {}

func (x *CommitVlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitVlogResponse.ProtoReflect.Descriptor instead.
func (*CommitVlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{17}
}

// Plog requests
type MakePlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        uint32                 `protobuf:"varint,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakePlogRequest) Reset() {
	*x = MakePlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakePlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakePlogRequest) ProtoMessage() {}

func (x *MakePlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakePlogRequest.ProtoReflect.Descriptor instead.
func (*MakePlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{18}
}

func (x *MakePlogRequest) GetDiskId() uint32 {
	if x != nil {
		return x.DiskId
	}
	return 0
}

type MakePlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlogId        uint32                 `protobuf:"varint,1,opt,name=plog_id,json=plogId,proto3" json:"plog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakePlogResponse) Reset() {
	*x = MakePlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakePlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakePlogResponse) ProtoMessage() {}

func (x *MakePlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakePlogResponse.ProtoReflect.Descriptor instead.
func (*MakePlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{19}
}

func (x *MakePlogResponse) GetPlogId() uint32 {
	if x != nil {
		return x.PlogId
	}
	return 0
}

type WritePlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlogId        uint32                 `protobuf:"varint,1,opt,name=plog_id,json=plogId,proto3" json:"plog_id,omitempty"`
	TxnId         int64                  `protobuf:"varint,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	LockId        int64                  `protobuf:"varint,3,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,4,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WritePlogRequest) Reset() {
	*x = WritePlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WritePlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WritePlogRequest) ProtoMessage() {}

func (x *WritePlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WritePlogRequest.ProtoReflect.Descriptor instead.
func (*WritePlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{20}
}

func (x *WritePlogRequest) GetPlogId() uint32 {
	if x != nil {
		return x.PlogId
	}
	return 0
}

func (x *WritePlogRequest) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *WritePlogRequest) GetLockId() int64 {
	if x != nil {
		return x.LockId
	}
	return 0
}

func (x *WritePlogRequest) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type WritePlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WritePlogResponse) Reset() {
	*x = WritePlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WritePlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WritePlogResponse) ProtoMessage() {}

func (x *WritePlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WritePlogResponse.ProtoReflect.Descriptor instead.
func (*WritePlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{21}
}

func (x *WritePlogResponse) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadPlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlogId        uint32                 `protobuf:"varint,1,opt,name=plog_id,json=plogId,proto3" json:"plog_id,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPlogRequest) Reset() {
	*x = ReadPlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPlogRequest) ProtoMessage() {}

func (x *ReadPlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPlogRequest.ProtoReflect.Descriptor instead.
func (*ReadPlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{22}
}

func (x *ReadPlogRequest) GetPlogId() uint32 {
	if x != nil {
		return x.PlogId
	}
	return 0
}

func (x *ReadPlogRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadPlogRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadPlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffer        []byte                 `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPlogResponse) Reset() {
	*x = ReadPlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPlogResponse) ProtoMessage() {}

func (x *ReadPlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPlogResponse.ProtoReflect.Descriptor instead.
func (*ReadPlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{23}
}

func (x *ReadPlogResponse) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type CommitPlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         int64                  `protobuf:"varint,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPlogRequest) Reset() {
	*x = CommitPlogRequest{}
	mi := &file_proto_rose_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPlogRequest) ProtoMessage() {}

func (x *CommitPlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPlogRequest.ProtoReflect.Descriptor instead.
func (*CommitPlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{24}
}

func (x *CommitPlogRequest) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

type CommitPlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPlogResponse) Reset() {
	*x = CommitPlogResponse{}
	mi := &file_proto_rose_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPlogResponse) ProtoMessage() {}

func (x *CommitPlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rose_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPlogResponse.ProtoReflect.Descriptor instead.
func (*CommitPlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_rose_proto_rawDescGZIP(), []int{25}
}

var File_proto_rose_proto protoreflect.FileDescriptor

const file_proto_rose_proto_rawDesc = "" +
	"\n" +
	"\x10proto/rose.proto\x12\arose.v1\"!\n" +
	"\vOpenRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"&\n" +
	"\fOpenResponse\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x03R\x06handle\">\n" +
	"\fWriteRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x03R\x06handle\x12\x16\n" +
	"\x06buffer\x18\x02 \x01(\fR\x06buffer\"\x0f\n" +
	"\rWriteResponse\"U\n" +
	"\vReadRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x03R\x06handle\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"&\n" +
	"\fReadResponse\x12\x16\n" +
	"\x06buffer\x18\x01 \x01(\fR\x06buffer\"$\n" +
	"\x0eGetattrRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"%\n" +
	"\x0fGetattrResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\"&\n" +
	"\fCloseRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x03R\x06handle\"\x0f\n" +
	"\rCloseResponse\"\x84\x01\n" +
	"\x0fMakeVlogRequest\x12+\n" +
	"\x11protection_scheme\x18\x01 \x01(\tR\x10protectionScheme\x12\x1f\n" +
	"\vdata_shards\x18\x02 \x01(\x05R\n" +
	"dataShards\x12#\n" +
	"\rparity_shards\x18\x03 \x01(\x05R\fparityShards\"+\n" +
	"\x10MakeVlogResponse\x12\x17\n" +
	"\avlog_id\x18\x01 \x01(\rR\x06vlogId\"Z\n" +
	"\x10WriteVlogRequest\x12\x17\n" +
	"\avlog_id\x18\x01 \x01(\rR\x06vlogId\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\x03R\x05txnId\x12\x16\n" +
	"\x06buffer\x18\x03 \x01(\fR\x06buffer\"+\n" +
	"\x11WriteVlogResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\"Z\n" +
	"\x0fReadVlogRequest\x12\x17\n" +
	"\avlog_id\x18\x01 \x01(\rR\x06vlogId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\"*\n" +
	"\x10ReadVlogResponse\x12\x16\n" +
	"\x06buffer\x18\x01 \x01(\fR\x06buffer\"*\n" +
	"\x11CommitVlogRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\x03R\x05txnId\"\x14\n" +
	"\x12CommitVlogResponse\"*\n" +
	"\x0fMakePlogRequest\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\rR\x06diskId\"+\n" +
	"\x10MakePlogResponse\x12\x17\n" +
	"\aplog_id\x18\x01 \x01(\rR\x06plogId\"s\n" +
	"\x10WritePlogRequest\x12\x17\n" +
	"\aplog_id\x18\x01 \x01(\rR\x06plogId\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\x03R\x05txnId\x12\x17\n" +
	"\alock_id\x18\x03 \x01(\x03R\x06lockId\x12\x16\n" +
	"\x06buffer\x18\x04 \x01(\fR\x06buffer\"+\n" +
	"\x11WritePlogResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\"Z\n" +
	"\x0fReadPlogRequest\x12\x17\n" +
	"\aplog_id\x18\x01 \x01(\rR\x06plogId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\"*\n" +
	"\x10ReadPlogResponse\x12\x16\n" +
	"\x06buffer\x18\x01 \x01(\fR\x06buffer\"*\n" +
	"\x11CommitPlogRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\x03R\x05txnId\"\x14\n" +
	"\x12CommitPlogResponse2\xb8\x06\n" +
	"\x04Rose\x123\n" +
	"\x04Open\x12\x14.rose.v1.OpenRequest\x1a\x15.rose.v1.OpenResponse\x126\n" +
	"\x05Write\x12\x15.rose.v1.WriteRequest\x1a\x16.rose.v1.WriteResponse\x123\n" +
	"\x04Read\x12\x14.rose.v1.ReadRequest\x1a\x15.rose.v1.ReadResponse\x126\n" +
	"\x05Close\x12\x15.rose.v1.CloseRequest\x1a\x16.rose.v1.CloseResponse\x12<\n" +
	"\aGetattr\x12\x17.rose.v1.GetattrRequest\x1a\x18.rose.v1.GetattrResponse\x12?\n" +
	"\bMakeVlog\x12\x18.rose.v1.MakeVlogRequest\x1a\x19.rose.v1.MakeVlogResponse\x12B\n" +
	"\tWriteVlog\x12\x19.rose.v1.WriteVlogRequest\x1a\x1a.rose.v1.WriteVlogResponse\x12?\n" +
	"\bReadVlog\x12\x18.rose.v1.ReadVlogRequest\x1a\x19.rose.v1.ReadVlogResponse\x12E\n" +
	"\n" +
	"CommitVlog\x12\x1a.rose.v1.CommitVlogRequest\x1a\x1b.rose.v1.CommitVlogResponse\x12?\n" +
	"\bMakePlog\x12\x18.rose.v1.MakePlogRequest\x1a\x19.rose.v1.MakePlogResponse\x12B\n" +
	"\tWritePlog\x12\x19.rose.v1.WritePlogRequest\x1a\x1a.rose.v1.WritePlogResponse\x12?\n" +
	"\bReadPlog\x12\x18.rose.v1.ReadPlogRequest\x1a\x19.rose.v1.ReadPlogResponse\x12E\n" +
	"\n" +
	"CommitPlog\x12\x1a.rose.v1.CommitPlogRequest\x1a\x1b.rose.v1.CommitPlogResponseB\x1cZ\x1agithub.com/rmmh/rose/protob\x06proto3"

var (
	file_proto_rose_proto_rawDescOnce sync.Once
	file_proto_rose_proto_rawDescData []byte
)

func file_proto_rose_proto_rawDescGZIP() []byte {
	file_proto_rose_proto_rawDescOnce.Do(func() {
		file_proto_rose_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rose_proto_rawDesc), len(file_proto_rose_proto_rawDesc)))
	})
	return file_proto_rose_proto_rawDescData
}

var file_proto_rose_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_rose_proto_goTypes = []any{
	(*OpenRequest)(nil),        // 0: rose.v1.OpenRequest
	(*OpenResponse)(nil),       // 1: rose.v1.OpenResponse
	(*WriteRequest)(nil),       // 2: rose.v1.WriteRequest
	(*WriteResponse)(nil),      // 3: rose.v1.WriteResponse
	(*ReadRequest)(nil),        // 4: rose.v1.ReadRequest
	(*ReadResponse)(nil),       // 5: rose.v1.ReadResponse
	(*GetattrRequest)(nil),     // 6: rose.v1.GetattrRequest
	(*GetattrResponse)(nil),    // 7: rose.v1.GetattrResponse
	(*CloseRequest)(nil),       // 8: rose.v1.CloseRequest
	(*CloseResponse)(nil),      // 9: rose.v1.CloseResponse
	(*MakeVlogRequest)(nil),    // 10: rose.v1.MakeVlogRequest
	(*MakeVlogResponse)(nil),   // 11: rose.v1.MakeVlogResponse
	(*WriteVlogRequest)(nil),   // 12: rose.v1.WriteVlogRequest
	(*WriteVlogResponse)(nil),  // 13: rose.v1.WriteVlogResponse
	(*ReadVlogRequest)(nil),    // 14: rose.v1.ReadVlogRequest
	(*ReadVlogResponse)(nil),   // 15: rose.v1.ReadVlogResponse
	(*CommitVlogRequest)(nil),  // 16: rose.v1.CommitVlogRequest
	(*CommitVlogResponse)(nil), // 17: rose.v1.CommitVlogResponse
	(*MakePlogRequest)(nil),    // 18: rose.v1.MakePlogRequest
	(*MakePlogResponse)(nil),   // 19: rose.v1.MakePlogResponse
	(*WritePlogRequest)(nil),   // 20: rose.v1.WritePlogRequest
	(*WritePlogResponse)(nil),  // 21: rose.v1.WritePlogResponse
	(*ReadPlogRequest)(nil),    // 22: rose.v1.ReadPlogRequest
	(*ReadPlogResponse)(nil),   // 23: rose.v1.ReadPlogResponse
	(*CommitPlogRequest)(nil),  // 24: rose.v1.CommitPlogRequest
	(*CommitPlogResponse)(nil), // 25: rose.v1.CommitPlogResponse
}
var file_proto_rose_proto_depIdxs = []int32{
	0,  // 0: rose.v1.Rose.Open:input_type -> rose.v1.OpenRequest
	2,  // 1: rose.v1.Rose.Write:input_type -> rose.v1.WriteRequest
	4,  // 2: rose.v1.Rose.Read:input_type -> rose.v1.ReadRequest
	8,  // 3: rose.v1.Rose.Close:input_type -> rose.v1.CloseRequest
	6,  // 4: rose.v1.Rose.Getattr:input_type -> rose.v1.GetattrRequest
	10, // 5: rose.v1.Rose.MakeVlog:input_type -> rose.v1.MakeVlogRequest
	12, // 6: rose.v1.Rose.WriteVlog:input_type -> rose.v1.WriteVlogRequest
	14, // 7: rose.v1.Rose.ReadVlog:input_type -> rose.v1.ReadVlogRequest
	16, // 8: rose.v1.Rose.CommitVlog:input_type -> rose.v1.CommitVlogRequest
	18, // 9: rose.v1.Rose.MakePlog:input_type -> rose.v1.MakePlogRequest
	20, // 10: rose.v1.Rose.WritePlog:input_type -> rose.v1.WritePlogRequest
	22, // 11: rose.v1.Rose.ReadPlog:input_type -> rose.v1.ReadPlogRequest
	24, // 12: rose.v1.Rose.CommitPlog:input_type -> rose.v1.CommitPlogRequest
	1,  // 13: rose.v1.Rose.Open:output_type -> rose.v1.OpenResponse
	3,  // 14: rose.v1.Rose.Write:output_type -> rose.v1.WriteResponse
	5,  // 15: rose.v1.Rose.Read:output_type -> rose.v1.ReadResponse
	9,  // 16: rose.v1.Rose.Close:output_type -> rose.v1.CloseResponse
	7,  // 17: rose.v1.Rose.Getattr:output_type -> rose.v1.GetattrResponse
	11, // 18: rose.v1.Rose.MakeVlog:output_type -> rose.v1.MakeVlogResponse
	13, // 19: rose.v1.Rose.WriteVlog:output_type -> rose.v1.WriteVlogResponse
	15, // 20: rose.v1.Rose.ReadVlog:output_type -> rose.v1.ReadVlogResponse
	17, // 21: rose.v1.Rose.CommitVlog:output_type -> rose.v1.CommitVlogResponse
	19, // 22: rose.v1.Rose.MakePlog:output_type -> rose.v1.MakePlogResponse
	21, // 23: rose.v1.Rose.WritePlog:output_type -> rose.v1.WritePlogResponse
	23, // 24: rose.v1.Rose.ReadPlog:output_type -> rose.v1.ReadPlogResponse
	25, // 25: rose.v1.Rose.CommitPlog:output_type -> rose.v1.CommitPlogResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rose_proto_init() }
func file_proto_rose_proto_init() {
	if File_proto_rose_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rose_proto_rawDesc), len(file_proto_rose_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rose_proto_goTypes,
		DependencyIndexes: file_proto_rose_proto_depIdxs,
		MessageInfos:      file_proto_rose_proto_msgTypes,
	}.Build()
	File_proto_rose_proto = out.File
	file_proto_rose_proto_goTypes = nil
	file_proto_rose_proto_depIdxs = nil
}
